# SPDX-License-Identifier: LGPL-3.0-or-later
# ruff: noqa: T201
r"""Sweep the launch-configuration tables of the shape-tuned SeZM kernels.

Every table served by :mod:`.tile_configs` is generated by this module.  A
sweep measures the candidate launch configurations of one kernel family for
one shape key on synthetic tensors at production edge counts, applies the
family's win rule, and returns the resulting entries (a configuration
tuple, or ``None`` where the family default is the measured optimum).

The module is used in three ways:

1. *Freeze auto-tuning* -- :func:`tune_missing_configs` sweeps exactly the
   shape keys a model needs that are absent from both the built-in tables
   and the current process registrations, and registers the winners via
   :func:`~.tile_configs.register_tile_configs`.  The SeZM ``.pt2`` freeze
   path calls this on the local GPU before tracing, so the frozen artifact
   bakes launches tuned for the deployment hardware even when the GPU has
   no built-in coverage.  Keys whose sweep concluded "keep the default"
   are registered as ``None`` and are not re-swept on later freezes.
2. *Manual sweeps* -- the CLI sweeps one explicit shape key
   (``--cf/--lmax``) or every key a checkpoint needs (``--model``), and
   prints the resulting entries as a Python fragment in the layout of
   :mod:`.tile_config_data`, ready to be merged under a new GPU name when
   extending the built-in tables.
3. *Table regeneration* -- rerunning a sweep after any kernel-body change;
   see the mandatory-validation note below.

Usage
-----
::

    python -m deepmd.pt_expt.kernels.triton.sezm.sweep_tile_configs \\
        --cf CF --lmax LMAX [--kernels FAMILY[,FAMILY...]] [--focus F]
        [--heads H] [--edges E] [--device cuda:0]

    python -m deepmd.pt_expt.kernels.triton.sezm.sweep_tile_configs \\
        --model model.pt [--level 3] [--edges E] [--device cuda:0]

``--kernels`` selects the sweep groups (default: all):

``pointwise``
    The gate / recompute / backward-pointwise kernels, keyed
    ``(focus_dim, lmax)`` -> the ``gate`` / ``recompute`` / ``point``
    families.  For ``cf >= GATE_BMM_MIN_FOCUS_DIM`` the gate projection
    runs as a cuBLAS bmm (reported once for reference) and the recompute
    kernel is not swept because it is never launched in that regime.
``point_recompute``
    The fused sigmoid-recompute + backward-pointwise kernel, keyed
    ``(focus_dim, lmax)`` -> ``point_recompute``.  The family is a win list:
    the fused kernel is recorded only when it beats the tuned separate
    projection and pointwise schedule by at least 3%.
``rotate_fwd``
    The rotate+mix forward kernel, keyed ``(C_wide, lmax)`` ->
    ``rotate_mix_fwd``; ``None`` records that the upstream default won.
``rotate_bwd``
    The edge-block rotate+mix backward against the per-edge kernel, keyed
    ``(C_wide, lmax)`` -> ``rotate_mix_bwd_block``.  The family is a win
    list: the entry is a configuration only when the speedup exceeds the
    3% noise margin, otherwise ``None`` keeps the per-edge kernel.
``flash_bwd``
    The edge-block flash-attention backward against the per-edge kernel,
    keyed ``(C_wide, lmax)`` -> ``flash_bwd_block``; the same win-list
    rule applies.
``fp32``
    The IEEE-fp32 mixing-stack GEMMs, keyed ``(focus_dim, lmax)`` ->
    ``stack_fp32``.  The ``m = 0`` forward, ``|m| = 1`` forward and combined
    backward kernels are timed independently because their matrix widths and
    epilogues place different pressure on a launch tile.
``m0_gate``
    The fp32 ``m = 0`` GEMM with its sigmoid projection and residual gate
    epilogue fused, keyed ``(focus_dim, lmax)`` -> ``stack_m0_gate``.  This
    register-heavy schedule is recorded only when it beats the tuned separate
    GEMM + projection + gate path by at least 3%.
``fp16x3``
    The four fp16x3 mixing-stack GEMMs, keyed ``(focus_dim, lmax)`` ->
    ``stack_fp16x3``.  Every candidate is ranked by standalone kernel time,
    validated end to end against an fp64 reference of the whole stack, then
    compared with the tuned fp32 stack over the full forward-plus-force-
    backward path.  ``None`` records that no candidate validated or that
    fp16x3 failed the 1% win margin.

Interpretation guidance
-----------------------
The winning ``BLOCK_M`` of the pointwise kernels and the winning ``BLOCK_E``
of the edge-block kernels shrink monotonically as the register-pressure
products ``lmax * next_power_of_2(cf)`` and ``lmax * next_power_of_2(C_wide)``
grow; a candidate on the wrong side of the spill point can be an order of
magnitude slower, which is why the tables are exact-keyed rather than
heuristic.  IEEE-fp32 stack configurations are validated against the
fallback because changing the K tile can regroup partial sums.  Winning
configurations are insensitive to the edge count once the device is saturated
(the defaults sweep at 6.5e5 edges); small systems are launch-bound and
insensitive to the choice altogether.

fp16x3 validation is mandatory
------------------------------
Some ``(num_warps, num_stages)`` combinations of the fp16x3 three-``tl.dot``
k-loop are miscompiled by the Triton software pipeliner into silent NaN rows.
The affected set shifts both with any change to the kernel body *and with the
edge count*: a config finite at one count can produce NaN at another, because
the miscompilation follows the launch grid rather than the data.  The fp16x3
sweep therefore validates every candidate through the full operator (forward
and force backward) in two ways before timing may crown it: an fp64 accuracy
check at a fixed count, and a finiteness check across an intermediate spread
of edge counts (``_FP16X3_FINITE_EDGES``) plus the main sweep count.  A
candidate that is inaccurate or non-finite at any of these is skipped.  The
edge-count spread reduces but cannot eliminate the risk (no finite sample
certifies every count), which is why ``num_stages == 1`` -- the
pipeliner-free family that is structurally NaN-free at any count -- stays in
the candidate grid.  Writing a hand-picked configuration into the tables
without this validation risks silently corrupted inference.  Sweeps at
``lmax >= 5`` compile deeply unrolled kernels and can take several minutes per
candidate; the reduced candidate grid keeps this tractable.
"""

from __future__ import (
    annotations,
)

import argparse
import itertools
import logging
import statistics
from contextlib import (
    contextmanager,
)
from dataclasses import (
    dataclass,
)
from typing import (
    TYPE_CHECKING,
    Any,
)

import torch
import triton
from torch.library import (
    wrap_triton,
)

if TYPE_CHECKING:
    from collections.abc import (
        Callable,
        Iterator,
    )
    from typing import (
        Literal,
    )

from deepmd.pt_expt.kernels.triton.sezm.flash_atten import (
    _flash_bwd_block_kernel,
    _flash_bwd_kernel,
    _flash_bwd_op,
)
from deepmd.pt_expt.kernels.triton.sezm.so2_stack_fp16x3 import (
    _mixing_stack_fp16x3_bwd_op,
    _mixing_stack_fp16x3_op,
    _split_fp16,
    _stack_fp16x3_bwd_kernel,
    _stack_fp16x3_m0_kernel,
    _stack_fp16x3_m1_kernel,
)
from deepmd.pt_expt.kernels.triton.sezm.so2_value_path import (
    _mixing_stack_bwd_op,
    _mixing_stack_op,
    _mixing_stack_reference,
    _rotate_mix_bwd_block_kernel,
    _rotate_mix_bwd_op,
    _rotate_mix_fwd_kernel,
    _stack_gate_kernel,
    _stack_gemm_m0_gate_kernel,
    _stack_gemm_bwd_kernel,
    _stack_gemm_m0_kernel,
    _stack_gemm_m1_kernel,
    _stack_point_bwd_kernel,
    _stack_recompute_kernel,
)
from deepmd.pt_expt.kernels.triton.sezm.tile_configs import (
    GATE_BMM_MIN_FOCUS_DIM,
    _STACK_GEMM_DEFAULT,
    _runtime_tile_configs,
    gate_config,
    has_tile_config,
    point_config,
    recompute_config,
    register_tile_configs,
    stack_fp32_configs,
)

__all__ = [
    "collect_model_shape_keys",
    "tune_missing_configs",
]

log = logging.getLogger(__name__)

_BLOCK_M_CANDIDATES = (8, 16, 32, 64)
_WARP_CANDIDATES = (4, 8, 16)
_STAGE_CANDIDATES = (1, 2)

# Edge-block winners never exceed BLOCK_E = 8 on any swept width (the
# per-edge register tile scales with BLOCK_E * C_wide, so larger blocks
# spill first), and every excluded candidate still costs a full Triton
# compilation -- minutes apiece on wide channels at high lmax.
_EDGE_BLOCK_CANDIDATES = tuple(itertools.product((2, 4, 8), (2, 4, 8), (1, 2)))
_ROTATE_FWD_DEFAULT = (2, 2)
_ROTATE_FWD_CANDIDATES = (
    (1, 1),
    (1, 2),
    (2, 1),
    _ROTATE_FWD_DEFAULT,
    (4, 1),
    (4, 2),
    (8, 2),
)
_FP32_GEMM_CANDIDATES = (
    _STACK_GEMM_DEFAULT,
    (64, 64, 32, 4, 3),
    (64, 64, 16, 4, 3),
    (32, 64, 64, 4, 1),
    (64, 32, 64, 4, 2),
    (32, 32, 32, 4, 1),
    (64, 32, 16, 4, 3),
    (128, 32, 32, 4, 2),
    (256, 32, 32, 8, 2),
    (64, 128, 32, 4, 2),
    (64, 128, 32, 4, 3),
    (64, 128, 16, 4, 3),
    (128, 64, 32, 4, 2),
    (128, 64, 16, 4, 3),
    (128, 128, 16, 4, 3),
    (128, 128, 32, 8, 3),
)
_FP16X3_GEMM_CANDIDATES = tuple(
    itertools.product((64, 128), (64, 128), (32, 64), (4, 8), (1, 2, 3))
)
# Whole-op pin candidates used to isolate one fp16x3 kernel during
# validation; the first combination that validates serves as the pin.
_FP16X3_PIN_CANDIDATES = (
    (64, 64, 32, 4, 1),
    (32, 64, 32, 4, 1),
    (64, 64, 64, 4, 1),
    (128, 64, 32, 8, 1),
    (64, 64, 32, 8, 2),
)
# Validated end-to-end error budgets, relative to the fp32 reference error
# on identical data (the fp32 rounding itself grows with the reduction
# width, so absolute thresholds mis-fire at wide shapes).
_FP16X3_TOL_FACTOR = 3.0
_FP16X3_CHECK_EDGES = 8192
# Edge counts at which every candidate's finiteness is re-checked (forward
# and backward), in addition to the accuracy check and the finiteness at the
# main sweep count.  The Triton software pipeliner can miscompile the
# three-``tl.dot`` k-loop into silent NaN at *some* edge counts while
# remaining finite at others -- the affected set shifts with the launch grid,
# so a single-edge-count check does not certify a config for the arbitrary
# edge counts an MD run presents.  This intermediate spread (below the main
# count, which is checked separately) samples the band where the
# miscompilation is launch-grid-sensitive.  ``num_stages == 1`` configs
# (pipeliner off, structurally NaN-free at any edge count) remain in the
# candidate grid because finite sampling cannot eliminate the risk.
_FP16X3_FINITE_EDGES = (4096, 20000, 65537, 131072)

# Route changes require a 3% win over the incumbent schedule.  Candidate
# ranking and stack-route selection use separate 1% margins because they
# encode independent selection policies.
_ROUTE_WIN_SPEEDUP = 1.03
_NEAR_FASTEST_FACTOR = 1.01
_STACK_WIN_SPEEDUP = 1.01

_DEFAULT_EDGES = 650000


def _saturating_edges(width: int) -> int:
    """Return a device-saturating edge count for the given channel width.

    Winning configurations are insensitive to the edge count once the device
    is saturated (measured winners are stable down to ~2e5 edges and start
    to drift below ~5e4), and the per-edge tensor footprint grows linearly
    with the channel width, so the sweep scales the synthetic edge count
    inversely with the width to keep peak memory roughly constant.  The
    reference point is 6.5e5 edges at width 64 -- the production scale the
    built-in tables were swept at.

    The count is additionally capped so the sweep's peak allocation stays
    within roughly a third of the device's total memory, keeping the freeze
    auto-tuner viable on small-memory GPUs and beside a resident model.
    The per-edge cost model (~160 KB per edge at width 64, scaling with the
    width) is the measured peak of the heaviest group -- the fp16x3 sweep,
    whose ranking buffers, fp64 validation reference and autograd graphs
    dwarf the synthetic tensors themselves.

    The memory budget always wins over tuning quality: measured winners are
    stable down to ~2e5 edges and drift only into neighboring near-optimal
    candidates below that (a few percent of kernel time, never correctness
    -- fp16x3 validity comes from the fp64 check, which is edge-count
    independent), so a reduced count merely costs a sliver of speed.  A
    sweep below 1e5 edges logs a notice to that effect; the hard floor of
    2e4 edges only keeps the timing signal above launch overhead.
    """
    edges = _DEFAULT_EDGES * 64 // max(width, 64)
    if torch.cuda.is_available():
        total = torch.cuda.get_device_properties(
            torch.cuda.current_device()
        ).total_memory
        bytes_per_edge = 160000 * max(width, 64) // 64
        cap = max(int(total / 3) // bytes_per_edge, 20000)
        if cap < min(edges, 100000):
            log.info(
                "Sweep edge count capped at %d by the device memory budget "
                "(device total %.1f GB); winning configurations may be a few "
                "percent off the saturated optimum.",
                cap,
                total / 2**30,
            )
        edges = min(edges, cap)
    return edges


# Entries returned by one sweep group: family name -> {shape key: entry}.
SweepResult = dict[str, dict[tuple[int, int], "tuple | None"]]
GemmConfig = tuple[int, int, int, int, int]


@contextmanager
def _runtime_config_scope(
    family: str, key: tuple[int, int]
) -> Iterator[Callable[[tuple | None], None]]:
    """Yield a config installer that restores prior state on failure."""
    runtime = _runtime_tile_configs(family)
    had_prior = key in runtime
    prior = runtime.get(key)

    def install(entry: tuple | None) -> None:
        register_tile_configs(family, {key: entry})

    try:
        yield install
    except BaseException:
        if had_prior:
            install(prior)
        else:
            runtime.pop(key, None)
        raise


def _bench(fn: Callable[[], object], iters: int = 20) -> float:
    """Return the mean kernel time of ``fn`` in milliseconds."""
    for _ in range(3):
        fn()
    torch.cuda.synchronize()
    start = torch.cuda.Event(enable_timing=True)
    stop = torch.cuda.Event(enable_timing=True)
    start.record()
    for _ in range(iters):
        fn()
    stop.record()
    torch.cuda.synchronize()
    return start.elapsed_time(stop) / iters


def _relerr(a: torch.Tensor, b: torch.Tensor) -> float:
    """Return the max relative error of ``a`` against reference ``b``."""
    return float((a - b).abs().max() / b.abs().max().clamp_min(1e-30))


def _block_diag_wigner(n_edge: int, lmax: int, device: torch.device) -> torch.Tensor:
    """Return a random block-diagonal Wigner-D stand-in with shape (E, D, D)."""
    dim = (lmax + 1) ** 2
    wigner = torch.zeros(n_edge, dim, dim, device=device, dtype=torch.float32)
    for degree in range(lmax + 1):
        base, size = degree * degree, 2 * degree + 1
        wigner[:, base : base + size, base : base + size] = torch.randn(
            n_edge, size, size, device=device
        )
    return wigner


# ======================================================================
# Pointwise group (gate / recompute / backward pointwise)
# ======================================================================
def sweep_pointwise(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep the gate / recompute / backward-pointwise launch triples.

    Parameters
    ----------
    cf : int
        Per-focus channel width ``Cf``.
    lmax : int
        Maximum spherical harmonic degree.
    n_focus : int
        Focus count of the synthetic tensors; the winners are valid for any
        focus count (the focus stream rides the grid batch axis).
    n_edge : int
        Edge count of the synthetic tensors.
    device : torch.device or str
        CUDA device to sweep on.

    Returns
    -------
    SweepResult
        Entries for ``gate``, ``point`` and (below the bmm regime)
        ``recompute`` under ``(cf, lmax)``.
    """
    device = torch.device(device)
    if n_edge is None:
        n_edge = _saturating_edges(cf)
    row = (3 * lmax + 1) * cf
    gate_width = lmax * cf
    use_bmm = cf >= GATE_BMM_MIN_FOCUS_DIM

    u = torch.randn(n_focus, n_edge, row, device=device)
    z_all = torch.randn(1, n_focus, n_edge, row, device=device)
    gw_all = torch.randn(1, n_focus, cf, gate_width, device=device) * 0.05
    gwt_all = gw_all.transpose(2, 3).contiguous()
    v = torch.empty_like(u)
    sig = torch.rand(n_focus, n_edge, gate_width, device=device, dtype=torch.float32)
    grad = torch.randn(n_focus, n_edge, row, device=device)
    gz = torch.empty_like(grad)
    glogit = torch.empty_like(sig) if use_bmm else sig

    def launch_point(bm: int, warps: int, stages: int) -> None:
        wrap_triton(_stack_point_bwd_kernel)[
            (triton.cdiv(n_edge, bm), n_focus)
        ](
            grad,
            z_all,
            sig,
            gwt_all,
            gz,
            glogit,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            GLOGIT_OUT=use_bmm,
            RECOMPUTE_SIG=False,
            BLOCK_M=bm,
            num_warps=warps,
            num_stages=stages,
        )

    kernels = {
        "gate": lambda bm, w, s: _stack_gate_kernel[(triton.cdiv(n_edge, bm), n_focus)](
            u,
            z_all,
            gw_all,
            v,
            sig,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            SIG_IN=use_bmm,
            BLOCK_M=bm,
            num_warps=w,
            num_stages=s,
        ),
        "recompute": lambda bm, w, s: _stack_recompute_kernel[
            (triton.cdiv(n_edge, bm), n_focus)
        ](
            z_all,
            gw_all,
            sig,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            BLOCK_M=bm,
            num_warps=w,
            num_stages=s,
        ),
        "point": launch_point,
    }
    if use_bmm:
        projection_ms = _bench(
            lambda: torch.sigmoid(torch.bmm(z_all[0, :, :, :cf], gw_all[0]), out=sig)
        )
        print(f"[bmm sigmoid projection: {projection_ms:.3f} ms]")
        kernels.pop("recompute")

    result: SweepResult = {}
    for family, launch in kernels.items():
        best_ms, best_cfg = float("inf"), None
        for bm, w, s in itertools.product(
            _BLOCK_M_CANDIDATES, _WARP_CANDIDATES, _STAGE_CANDIDATES
        ):
            try:
                ms = _bench(lambda: launch(bm, w, s))
            except triton.runtime.errors.OutOfResources:
                print(f"  BM={bm:3d} warps={w:2d} stages={s}: out of resources")
                continue
            marker = ""
            if ms < best_ms:
                best_ms, best_cfg = ms, (bm, w, s)
                marker = "  <-"
            print(f"  BM={bm:3d} warps={w:2d} stages={s}: {ms:8.3f} ms{marker}")
        print(f"BEST {family}[({cf}, {lmax})] = {best_cfg}  # {best_ms:.3f} ms")
        result[family] = {(cf, lmax): best_cfg}
    return result


def sweep_point_recompute(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep fused sigmoid recomputation against the tuned separate path.

    Parameters
    ----------
    cf : int
        Per-focus channel width ``Cf``.
    lmax : int
        Maximum spherical harmonic degree.
    n_focus : int
        Focus count of the synthetic tensors.
    n_edge : int or None
        Edge count; ``None`` selects a width-scaled saturating count.
    device : torch.device or str
        CUDA device used for the sweep.

    Returns
    -------
    SweepResult
        A single ``point_recompute`` win-list entry under ``(cf, lmax)``.
    """
    device = torch.device(device)
    if n_edge is None:
        n_edge = _saturating_edges(cf)
    row = (3 * lmax + 1) * cf
    gate_width = lmax * cf
    use_bmm = cf >= GATE_BMM_MIN_FOCUS_DIM

    z_all = torch.randn(1, n_focus, n_edge, row, device=device)
    gw_all = torch.randn(1, n_focus, cf, gate_width, device=device) * 0.05
    gwt_all = gw_all.transpose(2, 3).contiguous()
    sig = torch.empty(n_focus, n_edge, gate_width, device=device)
    grad = torch.randn(n_focus, n_edge, row, device=device)
    gz = torch.empty_like(grad)
    glogit = torch.empty_like(sig) if use_bmm else sig

    def launch_point(config: tuple[int, int, int], *, fused: bool) -> None:
        bm, warps, stages = config
        wrap_triton(_stack_point_bwd_kernel)[
            (triton.cdiv(n_edge, bm), n_focus)
        ](
            grad,
            z_all,
            sig,
            gwt_all,
            gz,
            glogit,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            GLOGIT_OUT=use_bmm,
            RECOMPUTE_SIG=fused,
            BLOCK_M=bm,
            num_warps=warps,
            num_stages=stages,
        )

    point = point_config(cf, lmax)
    if use_bmm:
        def project_sigmoid() -> None:
            torch.sigmoid(torch.bmm(z_all[0, :, :, :cf], gw_all[0]), out=sig)
    else:
        recompute = recompute_config(cf, lmax)

        def project_sigmoid() -> None:
            bm, warps, stages = recompute
            wrap_triton(_stack_recompute_kernel)[
                (triton.cdiv(n_edge, bm), n_focus)
            ](
                z_all,
                gw_all,
                sig,
                n_edge,
                0,
                L=lmax,
                CF=cf,
                BLOCK_M=bm,
                num_warps=warps,
                num_stages=stages,
            )

    def launch_separate() -> None:
        project_sigmoid()
        launch_point(point, fused=False)

    launch_separate()
    torch.cuda.synchronize()
    gz_reference = gz.clone()
    glogit_reference = glogit.clone() if use_bmm else None
    separate_ms = statistics.median(_bench(launch_separate) for _ in range(3))

    ranked: list[tuple[float, tuple[int, int, int]]] = []
    for config in itertools.product(
        _BLOCK_M_CANDIDATES, _WARP_CANDIDATES, _STAGE_CANDIDATES
    ):
        bm, warps, stages = config
        try:
            launch_point(config, fused=True)
            torch.cuda.synchronize()
            errors = [_relerr(gz, gz_reference)]
            if glogit_reference is not None:
                errors.append(_relerr(glogit, glogit_reference))
            if not bool(torch.isfinite(gz).all()) or max(errors) > 5e-6:
                print(
                    f"  BM={bm:3d} warps={warps:2d} stages={stages}: "
                    f"validation failed {errors}"
                )
                continue
            elapsed = statistics.median(
                _bench(lambda config=config: launch_point(config, fused=True))
                for _ in range(3)
            )
        except triton.runtime.errors.OutOfResources:
            print(
                f"  BM={bm:3d} warps={warps:2d} stages={stages}: "
                "out of resources"
            )
            continue
        ranked.append((elapsed, config))
        print(
            f"  BM={bm:3d} warps={warps:2d} stages={stages}: "
            f"{elapsed:8.3f} ms ({separate_ms / elapsed:.3f}x)"
        )

    ranked.sort()
    winner = None
    if ranked:
        fastest_ms = ranked[0][0]
        near_fastest = [
            (elapsed, config)
            for elapsed, config in ranked
            if elapsed <= fastest_ms * _NEAR_FASTEST_FACTOR
        ]
        selected_ms, selected = min(
            near_fastest, key=lambda item: (item[1][2], item[0])
        )
        if separate_ms / selected_ms >= _ROUTE_WIN_SPEEDUP:
            winner = selected
    print(
        f"BEST point_recompute[({cf}, {lmax})] = {winner}  # separate "
        f"{separate_ms:.3f} ms"
    )
    return {"point_recompute": {(cf, lmax): winner}}


# ======================================================================
# Rotate+mix forward
# ======================================================================
def sweep_rotate_fwd(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep the rotate+mix forward ``(num_warps, num_stages)`` pair.

    Returns the ``rotate_mix_fwd`` entry under the key
    ``(n_focus * cf, lmax)``; ``None`` records that the upstream default
    ``(2, 2)`` is the measured optimum.
    """
    device = torch.device(device)
    c_wide = n_focus * cf
    if n_edge is None:
        n_edge = _saturating_edges(c_wide)
    row = (3 * lmax + 1) * cf
    kernel_size = (lmax + 1) ** 2 + lmax**2
    n_nodes = max(n_edge // 128, 1)

    x = torch.randn(n_nodes, (lmax + 1) ** 2, c_wide, device=device)
    src = torch.randint(0, n_nodes, (n_edge,), device=device)
    wigner = _block_diag_wigner(n_edge, lmax, device)
    kc = torch.randn(n_edge, kernel_size, device=device)
    cb = torch.randn(1, c_wide, device=device)
    u = torch.empty(n_focus, n_edge, row, device=device, dtype=torch.float32)

    def launch(warps: int, stages: int) -> None:
        _rotate_mix_fwd_kernel[(n_edge,)](
            x,
            src,
            wigner,
            kc,
            cb,
            u,
            n_edge,
            x.stride(0),
            x.stride(1),
            L=lmax,
            CF=cf,
            CW=c_wide,
            BC=triton.next_power_of_2(c_wide),
            RANK=1,
            num_warps=warps,
            num_stages=stages,
        )

    best_ms, best_cfg = float("inf"), None
    for warps, stages in _ROTATE_FWD_CANDIDATES:
        try:
            ms = _bench(lambda: launch(warps, stages))
        except triton.runtime.errors.OutOfResources:
            continue
        marker = ""
        if ms < best_ms:
            best_ms, best_cfg = ms, (warps, stages)
            marker = "  <-"
        print(f"  warps={warps:2d} stages={stages}: {ms:8.3f} ms{marker}")
    entry = None if best_cfg == _ROTATE_FWD_DEFAULT else best_cfg
    print(
        f"BEST rotate_mix_fwd[({c_wide}, {lmax})] = {entry}  # {best_ms:.3f} ms"
        + ("  (upstream default)" if entry is None else "")
    )
    return {"rotate_mix_fwd": {(c_wide, lmax): entry}}


# ======================================================================
# Edge-block backward groups (win lists against the per-edge kernels)
# ======================================================================
def _win_list_entry(
    family: str, key: tuple[int, int], best: tuple[float, tuple] | None, base_ms: float
) -> tuple | None:
    """Apply the win rule: record the entry only above the 3% margin."""
    if best is None:
        print(f"BEST {family}[{key}]: no valid candidate; keep the per-edge kernel")
        return None
    speedup = base_ms / best[0]
    verdict = (
        "RECORD"
        if speedup >= _ROUTE_WIN_SPEEDUP
        else "keep the per-edge kernel"
    )
    print(
        f"BEST {family}[{key}] = {best[1]}  # {best[0]:.3f} ms vs per-edge "
        f"{base_ms:.3f} ms ({speedup:.2f}x) -> {verdict}"
    )
    return best[1] if speedup >= _ROUTE_WIN_SPEEDUP else None


def sweep_rotate_bwd(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep the edge-block rotate+mix backward against the per-edge kernel.

    Returns the ``rotate_mix_bwd_block`` win-list entry under the key
    ``(n_focus * cf, lmax)``.
    """
    device = torch.device(device)
    c_wide = n_focus * cf
    if n_edge is None:
        n_edge = _saturating_edges(c_wide)
    dim = (lmax + 1) ** 2
    row = (3 * lmax + 1) * cf
    kernel_size = (lmax + 1) ** 2 + lmax**2
    n_nodes = max(n_edge // 128, 1)

    grad_u = torch.randn(n_focus, n_edge, row, device=device)
    x = torch.randn(n_nodes, dim, c_wide, device=device)
    src = torch.randint(0, n_nodes, (n_edge,), device=device)
    wigner = _block_diag_wigner(n_edge, lmax, device)
    kc = torch.randn(n_edge, kernel_size, device=device)
    cb = torch.randn(1, c_wide, device=device)

    reference = _rotate_mix_bwd_op(grad_u, x, src, wigner, kc, cb, lmax, n_focus, 1)
    base_ms = _bench(
        lambda: _rotate_mix_bwd_op(grad_u, x, src, wigner, kc, cb, lmax, n_focus, 1),
        iters=8,
    )

    def launch(block_e: int, warps: int, stages: int) -> tuple[torch.Tensor, ...]:
        gxe = torch.empty(n_edge, dim, c_wide, device=device, dtype=torch.float32)
        gw = torch.zeros_like(wigner)
        gkc = torch.empty_like(kc)
        wrap_triton(_rotate_mix_bwd_block_kernel)[(triton.cdiv(n_edge, block_e),)](
            grad_u,
            x,
            src,
            wigner,
            kc,
            cb,
            gxe,
            gw,
            gkc,
            n_edge,
            x.stride(0),
            x.stride(1),
            L=lmax,
            CF=cf,
            CW=c_wide,
            CP=triton.next_power_of_2(c_wide),
            RANK=1,
            BLOCK_E=block_e,
            num_warps=warps,
            num_stages=stages,
        )
        return gxe, gw, gkc

    best = None
    for cfg in _EDGE_BLOCK_CANDIDATES:
        try:
            outputs = launch(*cfg)
            torch.cuda.synchronize()
            err = max(_relerr(o, r) for o, r in zip(outputs, reference))
            if err > 5e-6:
                continue
            ms = _bench(lambda: launch(*cfg), iters=8)
        except triton.runtime.errors.OutOfResources:
            continue
        if best is None or ms < best[0]:
            best = (ms, cfg)
            print(f"  BE={cfg[0]:3d} warps={cfg[1]} stages={cfg[2]}: {ms:8.3f} ms  <-")
    key = (c_wide, lmax)
    return {
        "rotate_mix_bwd_block": {
            key: _win_list_entry("rotate_mix_bwd_block", key, best, base_ms)
        }
    }


def sweep_flash_bwd(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_head: int = 1,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep the per-edge and edge-block flash-attention backward launches.

    Returns the ``flash_bwd_block`` win-list entry under the key
    ``(n_focus * cf, lmax)``.  The production per-edge winner is also returned
    as ``flash_bwd_edge`` so AOT freeze does not tune on its tiny trace sample.
    ``n_head`` only specializes the kernel binary through a ``constexpr``; the
    winning schedule is shared across head counts of the same width.
    """
    device = torch.device(device)
    c_wide = n_focus * cf
    if n_edge is None:
        n_edge = _saturating_edges(c_wide)
    dim = (lmax + 1) ** 2
    reduced_dim = 3 * lmax + 1
    n_nodes = max(n_edge // 128, 1)

    grad_pre_gate = torch.randn(n_nodes, dim, c_wide, device=device)
    x_local = torch.randn(n_edge, n_focus, reduced_dim, cf, device=device)
    wigner_dt = _block_diag_wigner(n_edge, lmax, device)
    rescale = torch.rand(dim, device=device, dtype=torch.float32) + 0.5
    alpha = torch.rand(n_edge, n_focus, n_head, device=device, dtype=torch.float32)
    dst = torch.randint(0, n_nodes, (n_edge,), device=device)

    reference = _flash_bwd_op(
        grad_pre_gate, x_local, wigner_dt, rescale, alpha, dst, lmax, n_head
    )

    def launch_edge(warps: int, stages: int) -> tuple[torch.Tensor, ...]:
        gxl = torch.empty_like(x_local)
        gdt = torch.zeros_like(wigner_dt)
        gw = torch.empty_like(alpha)
        wrap_triton(_flash_bwd_kernel.fn)[(n_edge,)](
            grad_pre_gate,
            x_local,
            wigner_dt,
            rescale,
            alpha,
            dst,
            gxl,
            gdt,
            gw,
            n_edge,
            c_wide,
            grad_pre_gate.stride(0),
            grad_pre_gate.stride(1),
            grad_pre_gate.stride(2),
            x_local.stride(0),
            x_local.stride(1),
            x_local.stride(2),
            x_local.stride(3),
            wigner_dt.stride(0),
            wigner_dt.stride(1),
            wigner_dt.stride(2),
            alpha.stride(0),
            alpha.stride(1),
            alpha.stride(2),
            gxl.stride(0),
            gxl.stride(1),
            gxl.stride(2),
            gxl.stride(3),
            gdt.stride(0),
            gdt.stride(1),
            gdt.stride(2),
            gw.stride(0),
            gw.stride(1),
            gw.stride(2),
            LMAX=lmax,
            CF=cf,
            HEAD_DIM=cf // n_head,
            NFOCUS=n_focus,
            NHEAD=n_head,
            BLOCK_C=triton.next_power_of_2(c_wide),
            num_warps=warps,
            num_stages=stages,
        )
        return gxl, gdt, gw

    edge_ranked: list[tuple[float, tuple[int, int]]] = []
    for edge_cfg in itertools.product((1, 2, 4), (1, 2)):
        outputs = launch_edge(*edge_cfg)
        torch.cuda.synchronize()
        err = max(_relerr(output, ref) for output, ref in zip(outputs, reference))
        if err > 5e-6:
            continue
        elapsed = statistics.median(
            _bench(lambda edge_cfg=edge_cfg: launch_edge(*edge_cfg), iters=8)
            for _ in range(3)
        )
        print(
            f"  edge warps={edge_cfg[0]} stages={edge_cfg[1]}: "
            f"{elapsed:8.3f} ms"
        )
        edge_ranked.append((elapsed, edge_cfg))
    if not edge_ranked:
        raise RuntimeError(f"no valid per-edge flash backward launch for {(c_wide, lmax)}")
    edge_ranked.sort()
    fastest_ms = edge_ranked[0][0]
    near_fastest = [
        (elapsed, config)
        for elapsed, config in edge_ranked
        if elapsed <= fastest_ms * _NEAR_FASTEST_FACTOR
    ]
    base_ms, edge_winner = min(
        near_fastest, key=lambda item: (item[1][0], item[1][1])
    )
    print(
        f"BEST flash_bwd_edge[{(c_wide, lmax)}] = {edge_winner}  # "
        f"{base_ms:.3f} ms"
    )

    def launch(block_e: int, warps: int, stages: int) -> tuple[torch.Tensor, ...]:
        gxl = torch.empty_like(x_local)
        gdt = torch.zeros_like(wigner_dt)
        gw = torch.empty_like(alpha)
        wrap_triton(_flash_bwd_block_kernel)[(triton.cdiv(n_edge, block_e),)](
            grad_pre_gate,
            x_local,
            wigner_dt,
            rescale,
            alpha,
            dst,
            gxl,
            gdt,
            gw,
            n_edge,
            grad_pre_gate.stride(0),
            grad_pre_gate.stride(1),
            x_local.stride(0),
            x_local.stride(1),
            x_local.stride(2),
            x_local.stride(3),
            gxl.stride(0),
            gxl.stride(1),
            gxl.stride(2),
            gxl.stride(3),
            L=lmax,
            CF=cf,
            CW=c_wide,
            CP=triton.next_power_of_2(c_wide),
            HEAD_DIM=cf // n_head,
            NHEAD=n_head,
            BLOCK_E=block_e,
            num_warps=warps,
            num_stages=stages,
        )
        return gxl, gdt, gw

    best = None
    for cfg in _EDGE_BLOCK_CANDIDATES:
        try:
            outputs = launch(*cfg)
            torch.cuda.synchronize()
            err = max(_relerr(o, r) for o, r in zip(outputs, reference))
            if err > 5e-6:
                continue
            ms = _bench(lambda: launch(*cfg), iters=8)
        except triton.runtime.errors.OutOfResources:
            continue
        if best is None or ms < best[0]:
            best = (ms, cfg)
            print(f"  BE={cfg[0]:3d} warps={cfg[1]} stages={cfg[2]}: {ms:8.3f} ms  <-")
    key = (c_wide, lmax)
    return {
        "flash_bwd_edge": {key: edge_winner},
        "flash_bwd_block": {key: _win_list_entry("flash_bwd_block", key, best, base_ms)}
    }


# ======================================================================
# IEEE-fp32 mixing-stack GEMMs
# ======================================================================
def _select_fp32_config(
    name: str,
    launch: Callable[[GemmConfig], None],
    candidates: tuple[GemmConfig, ...],
) -> GemmConfig:
    """Return a repeat-timed winner from a prefiltered GEMM shortlist."""
    for _ in range(20):
        launch(_STACK_GEMM_DEFAULT)
    torch.cuda.synchronize()

    ranked: list[tuple[float, GemmConfig]] = []
    for config in candidates:
        try:
            ranked.append((_bench(lambda config=config: launch(config), iters=6), config))
        except triton.runtime.errors.OutOfResources:
            continue
    if not ranked:
        raise RuntimeError(f"no launchable IEEE-fp32 GEMM candidate for {name}")
    ranked.sort()

    finalists = list(dict.fromkeys([config for _ms, config in ranked[:5]]))
    if _STACK_GEMM_DEFAULT not in finalists:
        finalists.append(_STACK_GEMM_DEFAULT)
    samples: dict[GemmConfig, list[float]] = {config: [] for config in finalists}
    for shift in range(3):
        ordered = finalists[shift:] + finalists[:shift]
        for config in ordered:
            samples[config].append(
                _bench(lambda config=config: launch(config), iters=20)
            )
    final = sorted(
        (statistics.median(times), config) for config, times in samples.items()
    )
    default_ms = next(
        ms for ms, config in final if config == _STACK_GEMM_DEFAULT
    )
    for ms, config in final:
        print(
            f"  {name} {config}: {ms:8.3f} ms "
            f"({default_ms / ms:.3f}x vs default)"
        )
    best_ms, best_config = final[0]
    if default_ms / best_ms < _STACK_WIN_SPEEDUP:
        best_ms, best_config = default_ms, _STACK_GEMM_DEFAULT
    print(f"BEST {name} = {best_config}  # {best_ms:.3f} ms")
    return best_config


def sweep_fp32(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep the three IEEE-fp32 mixing-stack GEMM configurations.

    The benchmark reproduces the three-layer production launch mix for each
    slot: two gated-layer launches plus one identity-layer launch in forward,
    and one final plus two gated-layer launches in backward.  The selected
    tuple is checked end to end against the conservative fallback before it is
    registered.
    """
    device = torch.device(device)
    if n_edge is None:
        n_edge = _saturating_edges(cf)
    n_layers = 3
    n_gated = n_layers - 1
    m0 = (lmax + 1) * cf
    m1 = 2 * lmax * cf
    row = (3 * lmax + 1) * cf
    gate_width = lmax * cf

    u0 = torch.randn(n_focus, n_edge, row, device=device)
    alpha = torch.rand(n_edge, n_focus, device=device) + 0.1
    w0_all = torch.randn(n_layers, n_focus, m0, m0, device=device) * 0.2
    w1_all = torch.randn(n_layers, n_focus, m1, m1, device=device) * 0.2
    w0t_all = w0_all.transpose(2, 3).contiguous()
    w1t_all = w1_all.transpose(2, 3).contiguous()
    gw_all = torch.randn(n_gated, n_focus, cf, gate_width, device=device) * 0.3
    gwt_all = gw_all.transpose(2, 3).contiguous()
    z_all = torch.empty(n_gated, n_focus, n_edge, row, device=device)
    focus_out = torch.empty_like(u0)
    edge_out = torch.empty(n_edge, n_focus, row, device=device)
    sig = torch.rand(n_focus, n_edge, gate_width, device=device)
    grad_edge = torch.randn(n_edge, n_focus, row, device=device)
    grad_focus = torch.randn_like(u0)
    residual = torch.randn_like(u0)
    grad_u = torch.empty_like(u0)

    def launch_m0(config: GemmConfig) -> None:
        bm, bn, bk, warps, stages = config
        grid = (triton.cdiv(n_edge, bm) * triton.cdiv(m0, bn), n_focus)
        for layer in range(n_gated):
            wrap_triton(_stack_gemm_m0_kernel)[grid](
                u0,
                w0_all,
                alpha,
                z_all,
                n_edge,
                layer,
                L=lmax,
                CF=cf,
                EPILOGUE=0,
                V_EDGE_MAJOR=False,
                APPLY_ALPHA=False,
                BLOCK_M=bm,
                BLOCK_N=bn,
                BLOCK_K=bk,
                num_warps=warps,
                num_stages=stages,
            )
        wrap_triton(_stack_gemm_m0_kernel)[grid](
            u0,
            w0_all,
            alpha,
            edge_out,
            n_edge,
            n_gated,
            L=lmax,
            CF=cf,
            EPILOGUE=1,
            V_EDGE_MAJOR=True,
            APPLY_ALPHA=True,
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            num_warps=warps,
            num_stages=stages,
        )

    def launch_m1(config: GemmConfig) -> None:
        bm, bn, bk, warps, stages = config
        grid = (triton.cdiv(n_edge, bm) * triton.cdiv(m1, bn), n_focus)
        for layer in range(n_gated):
            wrap_triton(_stack_gemm_m1_kernel)[grid](
                u0,
                w1_all,
                sig,
                alpha,
                focus_out,
                z_all,
                n_edge,
                layer,
                L=lmax,
                CF=cf,
                HAS_GATE=True,
                V_EDGE_MAJOR=False,
                APPLY_ALPHA=False,
                SAVE_Z=True,
                BLOCK_M=bm,
                BLOCK_N=bn,
                BLOCK_K=bk,
                num_warps=warps,
                num_stages=stages,
            )
        wrap_triton(_stack_gemm_m1_kernel)[grid](
            u0,
            w1_all,
            sig,
            alpha,
            edge_out,
            z_all,
            n_edge,
            n_gated,
            L=lmax,
            CF=cf,
            HAS_GATE=False,
            V_EDGE_MAJOR=True,
            APPLY_ALPHA=True,
            SAVE_Z=False,
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            num_warps=warps,
            num_stages=stages,
        )

    def launch_bwd(config: GemmConfig) -> None:
        bm, bn, bk, warps, stages = config
        n_tiles = triton.cdiv(m0, bn) + triton.cdiv(m1, bn)
        grid = (triton.cdiv(n_edge, bm) * n_tiles, n_focus)
        wrap_triton(_stack_gemm_bwd_kernel)[grid](
            grad_edge,
            grad_edge,
            w0t_all,
            w1t_all,
            alpha,
            grad_u,
            n_edge,
            n_gated,
            L=lmax,
            CF=cf,
            G_EDGE_MAJOR=True,
            FOLD_ALPHA=True,
            RES_IS_GZ=True,
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            num_warps=warps,
            num_stages=stages,
        )
        for layer in range(n_gated - 1, -1, -1):
            wrap_triton(_stack_gemm_bwd_kernel)[grid](
                grad_focus,
                residual,
                w0t_all,
                w1t_all,
                alpha,
                grad_u,
                n_edge,
                layer,
                L=lmax,
                CF=cf,
                G_EDGE_MAJOR=False,
                FOLD_ALPHA=False,
                RES_IS_GZ=False,
                BLOCK_M=bm,
                BLOCK_N=bn,
                BLOCK_K=bk,
                num_warps=warps,
                num_stages=stages,
            )

    m0_candidates = tuple(
        config for config in _FP32_GEMM_CANDIDATES if m0 % config[2] == 0
    )
    m1_candidates = tuple(
        config for config in _FP32_GEMM_CANDIDATES if m1 % config[2] == 0
    )
    bwd_candidates = tuple(
        config
        for config in _FP32_GEMM_CANDIDATES
        if m0 % config[2] == 0 and m1 % config[2] == 0
    )
    configs = (
        _select_fp32_config("stack fp32 forward m0", launch_m0, m0_candidates),
        _select_fp32_config("stack fp32 forward |m|=1", launch_m1, m1_candidates),
        _select_fp32_config("stack fp32 backward", launch_bwd, bwd_candidates),
    )

    key = (cf, lmax)

    with _runtime_config_scope("stack_fp32", key) as install:
        n_check = min(n_edge, 4096)
        u_check = u0[:, :n_check].contiguous()
        alpha_check = alpha[:n_check].contiguous()
        grad_check = grad_edge[:n_check].contiguous()
        fallback = (_STACK_GEMM_DEFAULT,) * 3
        install(fallback)
        x_ref, z_ref = _mixing_stack_op(
            u_check, alpha_check, w0_all, w1_all, gw_all, lmax, cf, True
        )
        gu_ref, ga_ref = _mixing_stack_bwd_op(
            grad_check,
            x_ref,
            z_ref,
            alpha_check,
            w0t_all,
            w1t_all,
            gw_all,
            gwt_all,
            lmax,
            cf,
            True,
        )
        install(configs)
        x_run, z_run = _mixing_stack_op(
            u_check, alpha_check, w0_all, w1_all, gw_all, lmax, cf, True
        )
        gu_run, ga_run = _mixing_stack_bwd_op(
            grad_check,
            x_run,
            z_run,
            alpha_check,
            w0t_all,
            w1t_all,
            gw_all,
            gwt_all,
            lmax,
            cf,
            True,
        )
        tensors = (x_run, z_run, gu_run, ga_run)
        errors = tuple(
            _relerr(actual, expected)
            for actual, expected in zip(tensors, (x_ref, z_ref, gu_ref, ga_ref))
        )
        if not all(bool(torch.isfinite(tensor).all()) for tensor in tensors):
            raise RuntimeError(f"non-finite IEEE-fp32 stack result for key {key}")
        if max(errors) > 5e-6:
            raise RuntimeError(
                f"IEEE-fp32 stack config validation failed for key {key}: "
                f"relative errors {errors}"
            )
        print(f"BEST stack_fp32[{key}] = {configs}  # errors {errors}")
        install(configs)
    return {"stack_fp32": {key: configs}}


def sweep_m0_gate(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep the fused fp32 m0-GEMM and forward-gate schedule.

    Parameters
    ----------
    cf : int
        Per-focus channel width ``Cf``.
    lmax : int
        Maximum spherical harmonic degree.
    n_focus : int
        Focus count of the synthetic tensors.
    n_edge : int or None
        Edge count; ``None`` selects a width-scaled saturating count.
    device : torch.device or str
        CUDA device used for the sweep.

    Returns
    -------
    SweepResult
        One ``stack_m0_gate`` win-list entry under ``(cf, lmax)``.
    """
    device = torch.device(device)
    if n_edge is None:
        n_edge = _saturating_edges(cf)
    row = (3 * lmax + 1) * cf
    m0 = (lmax + 1) * cf
    gate_width = lmax * cf
    use_bmm = cf >= GATE_BMM_MIN_FOCUS_DIM

    u = torch.randn(n_focus, n_edge, row, device=device)
    w0 = torch.randn(1, n_focus, m0, m0, device=device) * 0.2
    gw = torch.randn(1, n_focus, cf, gate_width, device=device) * 0.05
    z = torch.empty(1, n_focus, n_edge, row, device=device)
    v = torch.empty_like(u)
    sig = torch.empty(n_focus, n_edge, gate_width, device=device)
    m0_cfg = stack_fp32_configs(cf, lmax)[0]
    gate_cfg = gate_config(cf, lmax)

    def launch_separate() -> None:
        bm, bn, bk, warps, stages = m0_cfg
        wrap_triton(_stack_gemm_m0_kernel)[
            (triton.cdiv(n_edge, bm) * triton.cdiv(m0, bn), n_focus)
        ](
            u,
            w0,
            u,
            z,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            EPILOGUE=0,
            V_EDGE_MAJOR=False,
            APPLY_ALPHA=False,
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            num_warps=warps,
            num_stages=stages,
        )
        if use_bmm:
            torch.sigmoid(torch.bmm(z[0, :, :, :cf], gw[0]), out=sig)
        bm, warps, stages = gate_cfg
        wrap_triton(_stack_gate_kernel)[(triton.cdiv(n_edge, bm), n_focus)](
            u,
            z,
            gw,
            v,
            sig,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            SIG_IN=use_bmm,
            BLOCK_M=bm,
            num_warps=warps,
            num_stages=stages,
        )

    launch_separate()
    torch.cuda.synchronize()
    references = (z[0, :, :, :m0].clone(), v[:, :, :m0].clone(), sig.clone())
    separate_ms = statistics.median(_bench(launch_separate) for _ in range(3))

    block_k = 32 if m0 % 32 == 0 else 16
    ranked: list[tuple[float, tuple[int, int, int, int]]] = []
    for bm, warps in itertools.product(_BLOCK_M_CANDIDATES, (4, 8)):
        config = (bm, block_k, warps, 1)

        def launch() -> None:
            bm, bk, warps, stages = config
            wrap_triton(_stack_gemm_m0_gate_kernel)[
                (triton.cdiv(n_edge, bm), n_focus)
            ](
                u,
                w0,
                gw,
                v,
                z,
                sig,
                n_edge,
                0,
                L=lmax,
                CF=cf,
                BLOCK_M=bm,
                BLOCK_K=bk,
                num_warps=warps,
                num_stages=stages,
            )

        try:
            launch()
            torch.cuda.synchronize()
            outputs = (z[0, :, :, :m0], v[:, :, :m0], sig)
            error = max(_relerr(output, ref) for output, ref in zip(outputs, references))
            if not all(bool(torch.isfinite(output).all()) for output in outputs):
                continue
            if error > 5e-6:
                continue
            elapsed = statistics.median(_bench(launch) for _ in range(3))
        except triton.runtime.errors.OutOfResources:
            continue
        ranked.append((elapsed, config))
        print(f"  {config}: {elapsed:8.3f} ms ({separate_ms / elapsed:.3f}x)")

    ranked.sort()
    winner = None
    if ranked and separate_ms / ranked[0][0] >= _ROUTE_WIN_SPEEDUP:
        winner = ranked[0][1]
    print(
        f"BEST stack_m0_gate[{(cf, lmax)}] = {winner}  # separate "
        f"{separate_ms:.3f} ms"
    )
    return {"stack_m0_gate": {(cf, lmax): winner}}


# ======================================================================
# fp16x3 mixing-stack GEMMs (fp64-validated)
# ======================================================================
def sweep_fp16x3(
    cf: int,
    lmax: int,
    *,
    n_focus: int = 2,
    n_edge: int | None = None,
    device: torch.device | str = "cuda",
) -> SweepResult:
    """Sweep and validate the four fp16x3 stack GEMM configurations.

    Returns the ``stack_fp16x3`` entry under the key ``(cf, lmax)``:
    the fastest fp64-validated combination, or ``None`` when no candidate
    validates (the fp32 stack stays in charge).  Validation runs through
    the production operator, so trial configurations are registered into
    the runtime table during the sweep; the final conclusion is registered
    unconditionally on exit.
    """
    device = torch.device(device)
    if n_edge is None:
        n_edge = _saturating_edges(cf)
    n_layers = 3
    m0 = (lmax + 1) * cf
    m1 = 2 * lmax * cf
    half = lmax * cf
    row = (3 * lmax + 1) * cf

    u0 = torch.randn(n_focus, n_edge, row, device=device)
    alpha = torch.rand(n_edge, n_focus, device=device, dtype=torch.float32) + 0.1
    w0_all = torch.randn(n_layers, n_focus, m0, m0, device=device) * 0.2
    block_u = torch.randn(n_layers, n_focus, half, half, device=device) * 0.2
    block_v = torch.randn(n_layers, n_focus, half, half, device=device) * 0.2
    # The |m| = 1 weight carries the [[U, V], [-V, U]] complex structure of
    # SO2Linear so the synthetic stack matches the production operator.
    w1_all = torch.cat(
        [
            torch.cat([block_u, block_v], dim=3),
            torch.cat([-block_v, block_u], dim=3),
        ],
        dim=2,
    ).contiguous()
    gw_all = torch.randn(n_layers - 1, n_focus, cf, half, device=device) * 0.3
    w0h, w0l = _split_fp16(w0_all)
    w1h, w1l = _split_fp16(w1_all)
    w0t = w0_all.transpose(2, 3).contiguous()
    w1t = w1_all.transpose(2, 3).contiguous()
    gwt_all = gw_all.transpose(2, 3).contiguous()
    w0th, w0tl = _split_fp16(w0t)
    w1th, w1tl = _split_fp16(w1t)
    z_all = torch.empty(
        n_layers - 1, n_focus, n_edge, row, device=device, dtype=torch.float32
    )
    out = torch.empty_like(u0)
    sig = torch.full((n_focus, n_edge, half), 0.5, device=device, dtype=torch.float32)
    gz = torch.randn(n_focus, n_edge, row, device=device)
    g_res = torch.randn(n_focus, n_edge, row, device=device)
    gu = torch.empty_like(u0)

    def launch_m0(bm: int, bn: int, bk: int, warps: int, stages: int) -> None:
        wrap_triton(_stack_fp16x3_m0_kernel)[
            (triton.cdiv(n_edge, bm) * triton.cdiv(m0, bn), n_focus)
        ](
            u0,
            w0h,
            w0l,
            alpha,
            z_all,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            EPILOGUE=0,
            V_EDGE_MAJOR=False,
            APPLY_ALPHA=False,
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            num_warps=warps,
            num_stages=stages,
        )

    def launch_m1(bm: int, bn: int, bk: int, warps: int, stages: int) -> None:
        wrap_triton(_stack_fp16x3_m1_kernel)[
            (triton.cdiv(n_edge, bm) * triton.cdiv(m1, bn), n_focus)
        ](
            u0,
            w1h,
            w1l,
            sig,
            alpha,
            out,
            z_all,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            HAS_GATE=True,
            V_EDGE_MAJOR=False,
            APPLY_ALPHA=False,
            SAVE_Z=True,
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            num_warps=warps,
            num_stages=stages,
        )

    def launch_bwd(
        is_m1: bool, bm: int, bn: int, bk: int, warps: int, stages: int
    ) -> None:
        width = m1 if is_m1 else m0
        wh, wl = (w1th, w1tl) if is_m1 else (w0th, w0tl)
        wrap_triton(_stack_fp16x3_bwd_kernel)[
            (triton.cdiv(n_edge, bm) * triton.cdiv(width, bn), n_focus)
        ](
            gz,
            g_res,
            wh,
            wl,
            alpha,
            gu,
            n_edge,
            0,
            L=lmax,
            CF=cf,
            IS_M1=is_m1,
            G_EDGE_MAJOR=False,
            FOLD_ALPHA=False,
            RES_IS_GZ=False,
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            num_warps=warps,
            num_stages=stages,
        )

    launchers = {
        0: launch_m0,
        1: launch_m1,
        2: lambda *cfg: launch_bwd(False, *cfg),
        3: lambda *cfg: launch_bwd(True, *cfg),
    }
    names = ("forward m0", "forward |m|=1", "backward m0", "backward |m|=1")

    # === Step 1. Rank every candidate per kernel by standalone time ===
    ranked: dict[int, list[tuple[float, tuple]]] = {}
    for slot, launch in launchers.items():
        results = []
        for cfg in _FP16X3_GEMM_CANDIDATES:
            try:
                ms = _bench(lambda: launch(*cfg), iters=10)
            except triton.runtime.errors.OutOfResources:
                continue
            results.append((ms, cfg))
        results.sort()
        ranked[slot] = results

    # === Step 2. fp64 whole-op reference and validation harness ===
    n_check = min(_FP16X3_CHECK_EDGES, n_edge)
    truth_x, _ = _mixing_stack_reference(
        u0[:, :n_check].double(),
        alpha[:n_check].double(),
        w0_all.double(),
        w1_all.double(),
        gw_all.double(),
        lmax,
        cf,
        True,
    )
    truth_x = truth_x.float()
    u0_ref = u0[:, :n_check].double().requires_grad_(True)
    alpha_ref = alpha[:n_check].double().requires_grad_(True)
    x_ref, _ = _mixing_stack_reference(
        u0_ref,
        alpha_ref,
        w0_all.double(),
        w1_all.double(),
        gw_all.double(),
        lmax,
        cf,
        True,
    )
    grad_seed = torch.randn(n_check, n_focus, row, device=device)
    gu_ref, _ = torch.autograd.grad(x_ref, [u0_ref, alpha_ref], grad_seed.double())
    gu_ref = gu_ref.float()
    grad_pad = torch.zeros(n_edge, n_focus, row, device=device, dtype=torch.float32)
    grad_pad[:n_check] = grad_seed

    # Pre-built inputs for the cross-edge-count finiteness check (see
    # ``_FP16X3_FINITE_EDGES``).  Weights are edge-count independent, so only
    # the activation and the backward seed are rebuilt per count; counts at or
    # above the main sweep count are covered by ``whole_op_errors`` and skipped.
    finite_edges = [m for m in _FP16X3_FINITE_EDGES if m < n_edge]
    finite_inputs = [
        (
            torch.randn(n_focus, m, row, device=device),
            torch.rand(m, n_focus, device=device, dtype=torch.float32) + 0.1,
            torch.randn(m, n_focus, row, device=device),
        )
        for m in finite_edges
    ]

    def whole_op_errors() -> tuple[float, float, bool]:
        u0_run = u0.clone().requires_grad_(True)
        alpha_run = alpha.clone().requires_grad_(True)
        x_run, z_run = _mixing_stack_fp16x3_op(
            u0_run, alpha_run, w0_all, w1_all, gw_all, lmax, cf, True
        )
        finite = bool(torch.isfinite(x_run).all()) and bool(torch.isfinite(z_run).all())
        gu_run, _ = torch.autograd.grad(x_run, [u0_run, alpha_run], grad_pad)
        finite = finite and bool(torch.isfinite(gu_run).all())
        return (
            _relerr(x_run[:n_check], truth_x),
            _relerr(gu_run[:, :n_check], gu_ref),
            finite,
        )

    def finite_across_edges() -> bool:
        """Forward + backward finiteness of the installed config at the spread."""
        for u0_m, alpha_m, grad_m in finite_inputs:
            u0_r = u0_m.clone().requires_grad_(True)
            alpha_r = alpha_m.clone().requires_grad_(True)
            x_m, z_m = _mixing_stack_fp16x3_op(
                u0_r, alpha_r, w0_all, w1_all, gw_all, lmax, cf, True
            )
            if not (
                bool(torch.isfinite(x_m).all()) and bool(torch.isfinite(z_m).all())
            ):
                return False
            gu_m, _ = torch.autograd.grad(x_m, [u0_r, alpha_r], grad_m)
            if not bool(torch.isfinite(gu_m).all()):
                return False
        return True

    u0_fp32 = u0.clone().requires_grad_(True)
    alpha_fp32 = alpha.clone().requires_grad_(True)
    x_fp32, _ = _mixing_stack_op(
        u0_fp32, alpha_fp32, w0_all, w1_all, gw_all, lmax, cf, True
    )
    fp32_fwd_err = _relerr(x_fp32[:n_check], truth_x)
    gu_fp32, _ = torch.autograd.grad(x_fp32, [u0_fp32, alpha_fp32], grad_pad)
    fp32_bwd_err = _relerr(gu_fp32[:, :n_check], gu_ref)
    tol_fwd = max(_FP16X3_TOL_FACTOR * fp32_fwd_err, 2e-6)
    tol_bwd = max(_FP16X3_TOL_FACTOR * fp32_bwd_err, 8e-6)
    print(
        f"[fp32 reference errors: fwd {fp32_fwd_err:.2e}, bwd {fp32_bwd_err:.2e}; "
        f"tolerances fwd {tol_fwd:.2e}, bwd {tol_bwd:.2e}]"
    )

    def validate() -> bool:
        err_fwd, err_bwd, finite = whole_op_errors()
        if not (finite and err_fwd < tol_fwd and err_bwd < tol_bwd):
            return False
        # Accuracy and main-count finiteness hold; require finiteness across
        # the intermediate edge-count spread before accepting the config.
        return finite_across_edges()

    key = (cf, lmax)

    def conclude() -> tuple | None:
        """Validate candidates through the live table; return the winner."""
        # === Step 3. Find a pin combination that validates as a whole ===
        pin = None
        for candidate in _FP16X3_PIN_CANDIDATES:
            install((candidate,) * 4)
            if validate():
                pin = candidate
                break
        if pin is None:
            print(
                f"BEST stack_fp16x3[{key}]: no pin combination validates; "
                "the fp32 stack stays in charge"
            )
            return None
        print(f"[pin combination: {pin}]")

        # === Step 4. Per kernel, walk the speed ranking to the first
        # candidate that validates with the other three pinned ===
        chosen: list[tuple] = []
        for slot in range(4):
            picked = None
            for rank, (ms, cfg) in enumerate(ranked[slot]):
                entry = [pin] * 4
                entry[slot] = cfg
                install(tuple(entry))
                if validate():
                    picked = (ms, cfg, rank)
                    break
            if picked is None:
                print(
                    f"BEST stack_fp16x3[{key}]: {names[slot]} has no "
                    "validating candidate; the fp32 stack stays in charge"
                )
                return None
            chosen.append(picked)
            print(
                f"  {names[slot]}: rank #{picked[2]} {picked[1]} @ {picked[0]:.3f} ms"
            )

        # === Step 5. Joint validation; fall back to the pin on failure ===
        install(tuple(cfg for _ms, cfg, _rank in chosen))
        if not validate():
            print("[joint validation failed; falling back to the pin combination]")
            install((pin,) * 4)
            if not validate():
                print(
                    f"BEST stack_fp16x3[{key}]: pin combination regressed; "
                    "the fp32 stack stays in charge"
                )
                return None
            chosen = [(float("nan"), pin, -1)] * 4
        conclusion = tuple(cfg for _ms, cfg, _rank in chosen)
        print(f"BEST stack_fp16x3[{key}] = {conclusion}")
        return conclusion

    def wins_against_fp32() -> bool:
        """Return whether validated fp16x3 wins the whole force path."""
        grad_speed = torch.randn(n_edge, n_focus, row, device=device)
        x_fp32_speed, z_fp32_speed = _mixing_stack_op(
            u0, alpha, w0_all, w1_all, gw_all, lmax, cf, True
        )
        x_fp16_speed, z_fp16_speed = _mixing_stack_fp16x3_op(
            u0, alpha, w0_all, w1_all, gw_all, lmax, cf, True
        )

        def fp32_backward() -> tuple[torch.Tensor, torch.Tensor]:
            return _mixing_stack_bwd_op(
                grad_speed,
                x_fp32_speed,
                z_fp32_speed,
                alpha,
                w0t,
                w1t,
                gw_all,
                gwt_all,
                lmax,
                cf,
                True,
            )

        def fp16_backward() -> tuple[torch.Tensor, torch.Tensor]:
            return _mixing_stack_fp16x3_bwd_op(
                grad_speed,
                x_fp16_speed,
                z_fp16_speed,
                alpha,
                w0t,
                w1t,
                gw_all,
                gwt_all,
                lmax,
                cf,
                True,
            )

        timers = {
            "fp32 forward": lambda: _mixing_stack_op(
                u0, alpha, w0_all, w1_all, gw_all, lmax, cf, True
            ),
            "fp16x3 forward": lambda: _mixing_stack_fp16x3_op(
                u0, alpha, w0_all, w1_all, gw_all, lmax, cf, True
            ),
            "fp32 backward": fp32_backward,
            "fp16x3 backward": fp16_backward,
        }
        times = {
            name: statistics.median(_bench(fn, iters=10) for _ in range(3))
            for name, fn in timers.items()
        }
        fp32_ms = times["fp32 forward"] + times["fp32 backward"]
        fp16_ms = times["fp16x3 forward"] + times["fp16x3 backward"]
        speedup = fp32_ms / fp16_ms
        verdict = (
            "RECORD"
            if speedup >= _STACK_WIN_SPEEDUP
            else "keep the fp32 stack"
        )
        print(
            f"[stack whole force path: fp16x3 {fp16_ms:.3f} ms vs fp32 "
            f"{fp32_ms:.3f} ms ({speedup:.3f}x) -> {verdict}; "
            f"forward {times['fp16x3 forward']:.3f}/{times['fp32 forward']:.3f} "
            f"ms, backward {times['fp16x3 backward']:.3f}/"
            f"{times['fp32 backward']:.3f} ms]"
        )
        return speedup >= _STACK_WIN_SPEEDUP

    with _runtime_config_scope("stack_fp16x3", key) as install:
        conclusion = conclude()
        if conclusion is not None and not wins_against_fp32():
            conclusion = None
        install(conclusion)
    return {"stack_fp16x3": {key: conclusion}}


@dataclass(frozen=True)
class _SweepSpec:
    """Describe one independently covered launch-configuration sweep."""

    sweep: Callable[..., SweepResult]
    sentinel_family: str
    key_kind: Literal["focus", "wide"]
    min_level: int = 2
    accepts_heads: bool = False


_SWEEP_SPECS = {
    "pointwise": _SweepSpec(sweep_pointwise, "gate", "focus"),
    "point_recompute": _SweepSpec(
        sweep_point_recompute, "point_recompute", "focus"
    ),
    "rotate_fwd": _SweepSpec(sweep_rotate_fwd, "rotate_mix_fwd", "wide"),
    "rotate_bwd": _SweepSpec(
        sweep_rotate_bwd, "rotate_mix_bwd_block", "wide"
    ),
    "flash_bwd": _SweepSpec(
        sweep_flash_bwd, "flash_bwd_edge", "wide", accepts_heads=True
    ),
    "fp32": _SweepSpec(sweep_fp32, "stack_fp32", "focus"),
    "m0_gate": _SweepSpec(sweep_m0_gate, "stack_m0_gate", "focus"),
    "fp16x3": _SweepSpec(
        sweep_fp16x3, "stack_fp16x3", "focus", min_level=3
    ),
}


def _run_sweep(
    spec: _SweepSpec,
    cf: int,
    lmax: int,
    *,
    n_focus: int,
    n_head: int,
    n_edge: int | None,
    device: torch.device | str,
) -> SweepResult:
    """Run a sweep through its declarative argument contract."""
    kwargs: dict[str, Any] = {
        "n_focus": n_focus,
        "n_edge": n_edge,
        "device": device,
    }
    if spec.accepts_heads:
        kwargs["n_head"] = n_head
    return spec.sweep(cf, lmax, **kwargs)


# ======================================================================
# Model-driven tuning
# ======================================================================
_SO2_VALUE_PATH_ATTRIBUTES = (
    "lmax",
    "layer_scale",
    "mmax",
    "mixing_layers",
    "n_atten_head",
    "n_focus",
    "node_wise_grid_product",
    "non_linearities",
    "radial_degree_mixer",
    "so2_focus_dim",
    "so2_inter_norms",
    "so2_linears",
    "use_so2_attn_res",
)


def _has_so2_value_path_interface(module: torch.nn.Module) -> bool:
    """Return whether a module exposes the fused SO(2) value-path contract."""
    return all(hasattr(module, name) for name in _SO2_VALUE_PATH_ATTRIBUTES)


def collect_model_shape_keys(model: torch.nn.Module) -> list[tuple[int, int, int, int]]:
    """Collect the shape keys of every fused-value-path convolution in ``model``.

    Parameters
    ----------
    model : torch.nn.Module
        A constructed SeZM model (weights need not be loaded; the shapes are
        fixed by the hyperparameters).

    Returns
    -------
    list[tuple[int, int, int, int]]
        Deduplicated ``(focus_dim, lmax, n_focus, n_head)`` tuples, one per
        distinct convolution shape whose layout is supported by the fused
        value path.  Convolutions outside the supported layout never query
        the tables and contribute no keys.
    """
    from .so2_value_path import (
        _is_supported,
    )

    keys: list[tuple[int, int, int, int]] = []
    for module in model.modules():
        if not _has_so2_value_path_interface(module):
            continue
        conv: Any = module
        if not _is_supported(conv):
            continue
        n_head = conv.n_atten_head if conv.n_atten_head > 0 else 1
        key = (conv.so2_focus_dim, conv.lmax, conv.n_focus, n_head)
        if key not in keys:
            keys.append(key)
    return keys


def _load_model_params(model_path: str) -> dict[str, Any]:
    """Load model construction parameters from a Torch checkpoint."""
    raw = torch.load(model_path, map_location="cpu", weights_only=True)
    state_dict = raw.get("model", raw) if isinstance(raw, dict) else raw
    if not isinstance(state_dict, dict):
        raise ValueError(
            f"Unsupported checkpoint at '{model_path}': expected a state dictionary."
        )
    extra_state = state_dict.get("_extra_state")
    if not isinstance(extra_state, dict):
        raise ValueError(
            f"Unsupported checkpoint at '{model_path}': missing '_extra_state'."
        )
    model_params = extra_state.get("model_params")
    if not isinstance(model_params, dict):
        raise ValueError(
            f"Unsupported checkpoint at '{model_path}': missing "
            "'_extra_state.model_params'."
        )
    return model_params


def tune_missing_configs(
    shape_keys: list[tuple[int, int, int, int]],
    *,
    level: int,
    device: torch.device | str = "cuda",
    n_edge: int | None = None,
) -> SweepResult:
    """Sweep and register every table key the given shapes need but lack.

    For each ``(focus_dim, lmax, n_focus, n_head)`` shape, every sweep group
    relevant at the given ``DP_TRITON_INFER`` level (the table-configured
    kernels at level 2, plus the fp16x3 stack at level 3) is checked against
    :func:`~.tile_configs.has_tile_config` and run only when its sentinel
    key is absent from both the built-in tables and the current process
    registrations.  Results -- including "the default won" conclusions --
    are registered for the current process, so a subsequent trace bakes
    them and a subsequent call skips them.

    Parameters
    ----------
    shape_keys : list[tuple[int, int, int, int]]
        Shapes as returned by :func:`collect_model_shape_keys`.
    level : int
        The active Triton inference level; levels below 2 tune nothing.
    device : torch.device or str
        CUDA device to sweep on.
    n_edge : int or None
        Edge count of the synthetic sweep tensors; ``None`` selects a
        width-scaled saturating count per kernel family.

    Returns
    -------
    SweepResult
        All newly registered entries, empty when every key was covered.
    """
    registered: SweepResult = {}
    if level < 2:
        return registered
    for cf, lmax, n_focus, n_head in shape_keys:
        c_wide = n_focus * cf
        pending: list[tuple[str, _SweepSpec]] = []
        for group, spec in _SWEEP_SPECS.items():
            if level < spec.min_level:
                continue
            key = (cf, lmax) if spec.key_kind == "focus" else (c_wide, lmax)
            if has_tile_config(spec.sentinel_family, key):
                continue
            pending.append((group, spec))
        if not pending:
            continue
        log.info(
            "Tuning SeZM Triton launch configurations for shape "
            "(focus_dim=%d, lmax=%d, n_focus=%d) on %s: groups %s. "
            "This runs once per uncovered shape; expect minutes on narrow "
            "widths and up to tens of minutes on wide channels at high lmax "
            "(kernel compilation dominates).",
            cf,
            lmax,
            n_focus,
            torch.cuda.get_device_name(torch.device(device)),
            [group for group, _spec in pending],
        )
        for _group, spec in pending:
            result = _run_sweep(
                spec,
                cf,
                lmax,
                n_focus=n_focus,
                n_head=n_head,
                n_edge=n_edge,
                device=device,
            )
            for family, entries in result.items():
                register_tile_configs(family, entries)
                registered.setdefault(family, {}).update(entries)
            # Synthetic sweep tensors approach a third of the device memory;
            # returning them to the driver between groups keeps consecutive
            # sweeps (and the model being frozen) from fragmenting into OOM.
            torch.cuda.empty_cache()
    return registered


def _format_data_fragment(entries: SweepResult) -> str:
    """Render registered entries as a :mod:`.tile_config_data` fragment."""
    if not torch.cuda.is_available():
        return ""
    device_name = torch.cuda.get_device_name(torch.cuda.current_device())
    lines = [f'    "{device_name}": {{']
    for family in sorted(entries):
        lines.append(f'        "{family}": {{')
        for key in sorted(entries[family]):
            lines.append(f"            {key}: {entries[family][key]},")
        lines.append("        },")
    lines.append("    },")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sweep launch configurations of the shape-tuned SeZM "
        "Triton kernels, either for one explicit (cf, lmax) key or for "
        "every key a checkpoint needs."
    )
    parser.add_argument("--cf", type=int, help="per-focus width Cf")
    parser.add_argument("--lmax", type=int, help="maximum degree")
    parser.add_argument("--model", help="checkpoint path; sweeps its missing keys")
    parser.add_argument(
        "--level",
        type=int,
        default=3,
        help="tune for this DP_TRITON_INFER level (with --model)",
    )
    parser.add_argument("--focus", type=int, default=2, help="focus count F")
    parser.add_argument("--heads", type=int, default=1, help="attention head count")
    parser.add_argument(
        "--edges",
        type=int,
        default=None,
        help="edge count E (default: width-scaled saturating count)",
    )
    parser.add_argument("--device", default="cuda", help="CUDA device string")
    parser.add_argument(
        "--kernels",
        default=",".join(_SWEEP_SPECS),
        help=(
            "comma list of sweep groups (with --cf/--lmax), from "
            f"{sorted(_SWEEP_SPECS)}"
        ),
    )
    args = parser.parse_args()

    torch.manual_seed(0)
    torch.backends.cuda.matmul.allow_tf32 = False
    device = torch.device(args.device)
    if device.type == "cuda" and device.index is not None:
        torch.cuda.set_device(device)

    if args.model is not None:
        from deepmd.pt_expt.model.get_model import (
            get_model,
        )

        params = _load_model_params(args.model)
        branch_params = (
            list(params["model_dict"].values()) if "model_dict" in params else [params]
        )
        shape_keys = []
        for branch in branch_params:
            for key in collect_model_shape_keys(get_model(branch)):
                if key not in shape_keys:
                    shape_keys.append(key)
        print(f"model shape keys (cf, lmax, F, H): {shape_keys}")
        registered = tune_missing_configs(
            shape_keys, level=args.level, device=device, n_edge=args.edges
        )
    else:
        if args.cf is None or args.lmax is None:
            parser.error("either --model or both --cf and --lmax are required")
        groups = [name.strip() for name in args.kernels.split(",") if name.strip()]
        unknown = sorted(set(groups) - set(_SWEEP_SPECS))
        if unknown:
            parser.error(f"unknown sweep groups: {unknown}")
        print(
            f"cf={args.cf} lmax={args.lmax} focus={args.focus} heads={args.heads} "
            f"edges={args.edges}"
        )
        registered = {}
        for name in groups:
            print(f"== {name} ==")
            result = _run_sweep(
                _SWEEP_SPECS[name],
                args.cf,
                args.lmax,
                n_focus=args.focus,
                n_head=args.heads,
                n_edge=args.edges,
                device=device,
            )
            for family, entries in result.items():
                register_tile_configs(family, entries)
                registered.setdefault(family, {}).update(entries)

    if registered:
        print("\n# tile_config_data.py fragment (merge under the GPU name):")
        print(_format_data_fragment(registered))
    else:
        print("all requested keys are already covered; nothing swept")


if __name__ == "__main__":
    main()
