version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install -r doc/requirements.txt
formats: all
