name: Bug report
description: Create a bug report to help us eliminate issues and improve deepmd-kit.
title: "[BUG] _Replace With Suitable Title_"
labels: bug
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description: Please provide a clear and concise description of what the bug is.
      placeholder:
      value:
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: DeePMD-kit Version
      description: "`dp --version`"
    validations:
      required: true
  - type: input
    id: tf-version
    attributes:
      label: TensorFlow Version
      description: "The version will be printed when running DeePMD-kit."
    validations:
      required: true
  - type: dropdown
    id: installation-way
    attributes:
      label: How did you download the software?
      options:
        - Offline packages
        - conda
        - docker
        - pip
        - Built from source
        - Others (write below)
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Input Files, Running Commands, Error Log, etc.
      description: "Please provide necessary information including input file, running commands, error log , etc., AS  DETAILED AS POSSIBLE to help locate and reproduce your problem. WARNING: Do not use image to show error log! Paste texts in a code block instead."
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: "Describe the steps required to (quickly) reproduce the issue. You can attach (small) files to the section below or add URLs where to download an archive with all necessary files. Please try to create an input set that is as minimal and small as possible and reproduces the bug as quickly as possible. **NOTE:** the less effort and time it takes to reproduce your reported bug, the more likely it becomes, that somebody will look into it and fix the problem."
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: further
    attributes:
      label: Further Information, Files, and Links
      description: Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications
      placeholder:
      value:
    validations:
      required: false
