name: Feature request
description: Suggest an idea for this project.
title: "[Feature Request] _Replace with Title_"
labels: enhancement
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Please provide a brief and concise description of the suggested feature or change"
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Detailed Description
      description: "Please explain how you would like to see deepmd-kit enhanced, what feature(s) you are looking for, what specific problems this will solve. If possible, provide references to relevant background information like publications or web pages, and whether you are planning to implement the enhancement yourself or would like to participate in the implementation. If applicable add a reference to an existing bug report or issue that this will address."
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: further
    attributes:
      label: Further Information, Files, and Links
      description: Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications
      placeholder:
      value:
    validations:
      required: false
