name: Parameters
description: Make a suggestion for a change of input parameters or a new output to deepmd-kit.
title: "[Parameters] _Replace With Suitable Title_"
labels: documentation, enhancement
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Please provide a clear and concise description of what your request is."
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Detailed Description
      description: "Please explain how you would like to see deepmd-kit enhanced. Specify your material system, and exactly what behaviors or properties you are looking for, or what specific problems this will solve. If possible, provide references to relevant background information like publications or web pages, and whether you are planning to implement the enhancement yourself or would like to participate in the implementation."
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: further
    attributes:
      label: Further Information, Files, and Links
      description: Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications
      placeholder:
      value:
    validations:
      required: false
