# SPDX-License-Identifier: LGPL-3.0-or-later
"""LAMMPS ``pair_style deepspin`` on the COMBINED native-spin + ZBL-bridged
DPA4 NeighborGraph (graph-schema) ``.pt2``
(``deeppot_dpa4_spin_zbl_graph.pt2``, generated by
``source/tests/infer/gen_dpa4_spin_zbl.py``).

This pins the spin+ZBL variant end-to-end, which previously had NO LAMMPS
coverage at all: single-rank pair/virial against a LIVE ``DeepPot`` reference
computed at test-setup time on this module's own geometry, AND 2-rank vs
1-rank MPI parity -- including a close-pair geometry whose ~0.978 A Ni-Ni
pair straddles the ``processors 2 1 1`` domain boundary INSIDE the bridging
transition zone (the generator sets ``bridging_r_inner = 0.8`` /
``bridging_r_outer = 1.2``, verbatim from ``gen_dpa4_zbl.py``; 0.8 < 0.978 <
1.2).  Bridging enables the descriptor's Source Freeze Propagation Gate,
whose per-node ``[log_eta, zero_count]`` partials fold a node's FULL
outgoing-edge set; edges exist only for owned centres, so the partials are
rank-incomplete.  The SFPG cross-rank completion -- one reverse-accumulate
(``border_op_backward``) + forward-broadcast (``border_op``) exchange of the
per-node partials inside the with-comm artifact -- completes them before the
gate is applied, which is what makes bridged models multi-rank capable
(issue #5906).  The close-pair test is the geometry that actually exercises
that exchange: without a bridging-zone pair split across ranks the parity
comparison would be vacuous.

Reference (energy / force / force_mag / virial) values are computed LIVE at
test-setup time via ``deepmd.infer.DeepPot.eval`` on the archive for the
fixed 4-atom NiO system reused from ``test_lammps_dpa4_spin_graph_pt2.py``
(box 13x13x13, 2 spin-active Ni + 2 non-magnetic O) -- deliberately NOT
hardcoded (a hardcoded reference goes stale the moment DPA4 numerics shift)
and NOT read from the generator's ``.expected`` sidecar (its own 6-atom
system sits in a 6x6x6 box whose edge exactly equals DPA4's ghost cutoff --
not a safe geometry for a LAMMPS periodic run).  ``_compute_expected`` runs
in a subprocess so importing ``deepmd``'s Python package does not share a
process with the LAMMPS plugin's own loaded ``libdeepmd_op_pt.so`` (see
``test_lammps_model_devi_pt2.py``).
"""

import importlib.util
import json
import os
import shutil
import signal
import subprocess as sp
import sys
import tempfile
import textwrap
from pathlib import (
    Path,
)

import constants
import numpy as np
import pytest
from lammps import (
    PyLammps,
)
from write_lmp_data import (
    write_lmp_data_spin,
)

pb_file = (
    Path(__file__).parent.parent.parent
    / "tests"
    / "infer"
    / "deeppot_dpa4_spin_zbl_graph.pt2"
)
data_file = Path(__file__).parent / "data_dpa4_spin_zbl_pt2.lmp"
data_file_close_pair = Path(__file__).parent / "data_dpa4_spin_zbl_close_pair_pt2.lmp"
# The MPI runner is graph-spin-specific (no aparam / no NULL-type extras,
# unlike run_mpi_pair_deepmd_spin_dpa3_pt2.py's virtual-atom-scheme runner):
# the native-spin (+ZBL) DPA4 fixtures take no fparam/aparam, so the plain
# native-spin runner is reused verbatim -- only the archive differs.
mpi_runner = Path(__file__).parent / "run_mpi_pair_deepmd_spin_graph_dpa4_pt2.py"

_MPI_DEFAULT_TIMEOUT = 120.0

# Same 4-atom NiO system as test_lammps_dpa4_spin_graph_pt2.py (box,
# coordinates, and LAMMPS type ordering all reused verbatim): 2 Ni atoms
# (LAMMPS type 1, deepmd atype 0, spin-active) + 2 O atoms (LAMMPS type 2,
# deepmd atype 1, non-magnetic) -- matches the archive's
# ``type_map=["Ni", "O"]`` and ``use_spin=[True, False]``
# (gen_dpa4_spin_zbl.py inherits both from gen_dpa4_spin.py).  The Ni-Ni
# pair (atoms 0 and 1) sits ~0.978 A apart -- inside the bridging
# transition zone (0.8, 1.2), so the ZBL channel is active even in the
# single-rank tests.
box = np.array([0, 13, 0, 13, 0, 13, 0, 0, 0])
coord = np.array(
    [
        [12.83, 2.56, 2.18],
        [12.09, 2.87, 2.74],
        [3.51, 2.51, 2.60],
        [4.27, 3.22, 1.56],
    ]
)
spin = np.array(
    [
        [0, 0, 1.2737],
        [0, 0, 1.2737],
        [0, 0, 0],
        [0, 0, 0],
    ]
)
type_NiO = np.array([1, 1, 2, 2])

# Close-pair geometry for the MPI-parity test: the SAME 4-atom system
# shifted along x by -5.9, so the ~0.978 A Ni-Ni pair lands at x = 6.93 /
# 6.19 -- straddling the lx/2 = 6.5 domain boundary of ``processors 2 1 1``.
# The shift pushes atom 2 (x = 3.51) below zero, so the x column is wrapped
# back into the periodic box with ``np.mod(x, 13)`` (LAMMPS is periodic, so
# wrapping changes nothing physically; it just keeps the data file's
# coordinates inside [0, lx) as write_lmp_data_spin expects).
_CLOSE_PAIR_SHIFT_X = -5.9
coord_close_pair = coord.copy()
coord_close_pair[:, 0] = np.mod(coord[:, 0] + _CLOSE_PAIR_SHIFT_X, box[1])

# LAMMPS's ``fm`` (what ``compute property/atom fmx fmy fmz`` reports) is
# NOT the raw DeepEval force_mag: pair_deepspin.cpp scales it by
# ``spin_norm / hbar`` per atom (metal-units ``hbar = 6.5821191e-04``, see
# ``source/lmp/pair_deepspin.cpp:531,535``).  ``spin_norm`` is 0 for the two
# non-magnetic O atoms, so the scaling is a no-op there (0 stays 0).
_HBAR_METAL = 6.5821191e-04

# Reference values (energy / atom-energy / force / force_mag / virial),
# populated by ``_compute_expected`` in ``setup_module`` -- see the module
# docstring for why these are computed live via a DeepPot subprocess call
# rather than hardcoded or read from a sidecar file.
expected_e = None
expected_ae = None
expected_f = None
expected_fm = None
expected_v = None


def _cell_from_lammps_box(lmp_box: np.ndarray) -> np.ndarray:
    """Convert a LAMMPS ``xlo xhi ylo yhi zlo zhi xy xz yz`` box spec to a
    flat, row-major 3x3 cell matrix (deepmd's ``box`` convention).
    """
    xlo, xhi, ylo, yhi, zlo, zhi, xy, xz, yz = lmp_box
    return np.array(
        [
            xhi - xlo,
            0.0,
            0.0,
            xy,
            yhi - ylo,
            0.0,
            xz,
            yz,
            zhi - zlo,
        ]
    )


def _compute_expected() -> None:
    """Load ``deeppot_dpa4_spin_zbl_graph.pt2`` via ``DeepPot`` and evaluate
    the module's fixed 4-atom NiO system to obtain the Python reference.

    Runs in a subprocess to avoid importing ``deepmd`` in the LAMMPS test
    process (see ``test_lammps_model_devi_pt2.py``'s ``_compute_expected``
    for the same precaution: the LAMMPS plugin already loads
    ``libdeepmd_op_pt.so`` at the C++ level, and importing the Python
    package on top of that can segfault).
    """
    global expected_e, expected_ae, expected_f, expected_fm, expected_v

    cell = _cell_from_lammps_box(box)
    atype = (type_NiO - 1).tolist()  # LAMMPS 1-based -> deepmd 0-based (Ni=0, O=1)

    # The archive lives in ``source/tests/infer`` next to ``gen_common.py``,
    # whose ``load_custom_ops()`` loads the build-tree ``libdeepmd_op_pt.so``
    # (registering ``deepmd::edge_force_virial``, which the graph ``.pt2``
    # inference needs). ``import deepmd.pt`` alone only loads the op library
    # from SHARED_LIB_DIR, which the build-test env does not populate -- so
    # the subprocess reuses that fallback (after importing ``deepmd.pt``, per
    # its docstring) before constructing ``DeepPot``.
    infer_dir = str(pb_file.resolve().parent)
    script = textwrap.dedent(f"""\
        import json
        import sys
        import numpy as np

        sys.path.insert(0, {infer_dir!r})
        import deepmd.pt  # noqa: F401  (triggers the base op-library load)
        from gen_common import load_custom_ops

        load_custom_ops()
        from deepmd.infer import DeepPot

        dp = DeepPot({str(pb_file.resolve())!r})
        e, f, v, ae, av, fm, mm = dp.eval(
            np.array({coord.tolist()!r}).reshape(1, -1, 3),
            np.array({cell.tolist()!r}).reshape(1, 9),
            {atype!r},
            atomic=True,
            spin=np.array({spin.tolist()!r}).reshape(1, -1, 3),
        )
        print(json.dumps({{
            "e": float(e[0, 0]),
            "ae": np.asarray(ae[0]).reshape(-1).tolist(),
            "f": np.asarray(f[0]).tolist(),
            "fm": np.asarray(fm[0]).tolist(),
            "av": np.asarray(av[0]).tolist(),
        }}))
    """)
    proc = sp.run(
        [sys.executable, "-c", script],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"Failed to compute expected values:\n{proc.stderr}")
    result = json.loads(proc.stdout.strip())

    expected_e = result["e"]
    expected_ae = np.array(result["ae"])
    expected_f = np.array(result["f"])
    # Raw DeepEval force_mag (dE/dspin), scaled by LAMMPS's own
    # spin_norm / hbar unit convention (see the comment on ``_HBAR_METAL``
    # above) before comparison.
    fm_raw = np.array(result["fm"])
    spin_norm = np.linalg.norm(spin, axis=1)
    expected_fm = fm_raw * (spin_norm / _HBAR_METAL)[:, None]
    # Per-atom virial, sign-flipped (LAMMPS convention) relative to DeepPot's
    # atomic virial output (mirrors test_lammps_spin_pt2.py's convention).
    expected_v = -np.array(result["av"])


def setup_module() -> None:
    if os.environ.get("ENABLE_PYTORCH", "1") != "1":
        pytest.skip(
            "Skip test because PyTorch support is not enabled.",
        )
    if not pb_file.exists():
        pytest.skip("deeppot_dpa4_spin_zbl_graph.pt2 not found")
    _compute_expected()
    write_lmp_data_spin(box, coord, spin, type_NiO, data_file)
    write_lmp_data_spin(box, coord_close_pair, spin, type_NiO, data_file_close_pair)


def teardown_module() -> None:
    for path in (data_file, data_file_close_pair):
        if path.exists():
            os.remove(path)


def _lammps(data_file, units="metal") -> PyLammps:
    """Standard DeepSpin LAMMPS system, plus ``atom_modify map yes``.

    Mirrors ``lammps_test_utils.make_spin_lammps`` (not reused directly: it
    does not set ``atom_modify``), with the map turned on -- the native-spin
    DPA4 GRAPH ``.pt2`` needs the LAMMPS atom-map to resolve ghost-atom
    indices to local owners for single-rank inference (same requirement as
    the energy graph route; see ``pair_deepspin.cpp``'s
    ``DeePMD-kit Error: Single-rank LAMMPS .pt2 inference requires
    `atom_modify map yes``` check).
    """
    if units != "metal":
        raise ValueError("units for spin should be metal")

    lammps = PyLammps()
    lammps.units(units)
    lammps.boundary("p p p")
    lammps.atom_style("spin")
    lammps.atom_modify("map yes")
    lammps.neighbor("2.0 bin")
    lammps.neigh_modify("every 10 delay 0 check no")
    lammps.read_data(data_file.resolve())
    lammps.mass("1 58")
    lammps.mass("2 16")
    lammps.timestep(0.0005)
    lammps.fix("1 all nve")
    return lammps


@pytest.fixture
def lammps():
    lmp = _lammps(data_file=data_file)
    yield lmp
    lmp.close()


def _gather_force_mag(lammps: PyLammps, natoms: int) -> np.ndarray:
    """Extract per-atom force_mag in atom-id order.

    LAMMPS does not expose ``fm`` through the legacy ``extract``/
    ``gather_atoms`` registry (see ``run_mpi_pair_deepmd_spin_dpa3_pt2.py``'s
    module docstring), so go via ``compute property/atom fmx fmy fmz`` +
    ``gather`` (id-ordered on every rank, single-rank included).
    """
    fm_global = lammps.lmp.gather("c_fmprop", 1, 3)
    return np.array(fm_global, dtype=np.float64).reshape(natoms, 3)


def test_pair_deepspin(lammps) -> None:
    """Single-rank LAMMPS energy + force + force_mag vs the Python DeepEval
    reference on the spin+ZBL archive, on the same 4-atom NiO system.
    """
    lammps.pair_style(f"deepspin {pb_file.resolve()}")
    lammps.pair_coeff("* *")
    lammps.compute("fmprop all property/atom fmx fmy fmz")
    lammps.run(0)

    assert lammps.eval("pe") == pytest.approx(expected_e)

    forces = np.array([lammps.atoms[ii].force for ii in range(4)], dtype=np.float64)
    ids = np.array([lammps.atoms[ii].id for ii in range(4)])
    order = np.argsort(ids)
    forces = forces[order]
    np.testing.assert_allclose(forces, expected_f, atol=1e-8, rtol=0)

    force_mag = _gather_force_mag(lammps, coord.shape[0])
    np.testing.assert_allclose(force_mag, expected_fm, atol=1e-8, rtol=0)
    # Anti-vacuity / native-spin design invariant: force_mag on the two
    # non-spin (O) atoms must be exactly zero, both in the Python reference
    # (baked into expected_fm above) and as produced by LAMMPS.  The
    # analytical ZBL child, which knows nothing about spin, must not leak
    # into this channel either.
    np.testing.assert_array_equal(force_mag[2:], np.zeros((2, 3)))

    lammps.run(1)


def test_pair_deepspin_virial(lammps) -> None:
    """Single-rank per-atom pe/pressure/virial via
    ``pe/atom`` / ``pressure`` / ``centroid/stress/atom``, atol=1e-8,
    rtol=1e-8.
    """
    lammps.pair_style(f"deepspin {pb_file.resolve()}")
    lammps.pair_coeff("* *")
    lammps.compute("peatom all pe/atom pair")
    lammps.compute("pressure all pressure NULL pair")
    lammps.compute("virial all centroid/stress/atom NULL pair")
    lammps.variable("eatom atom c_peatom")
    for ii in range(9):
        jj = [0, 4, 8, 3, 6, 7, 1, 2, 5][ii]
        lammps.variable(f"pressure{jj} equal c_pressure[{ii + 1}]")
    for ii in range(9):
        jj = [0, 4, 8, 3, 6, 7, 1, 2, 5][ii]
        lammps.variable(f"virial{jj} atom c_virial[{ii + 1}]")
    lammps.dump(
        "1 all custom 1 dump id " + " ".join([f"v_virial{ii}" for ii in range(9)])
    )
    lammps.run(0)

    assert lammps.eval("pe") == pytest.approx(expected_e)

    forces = np.array([lammps.atoms[ii].force for ii in range(4)], dtype=np.float64)
    ids = np.array([lammps.atoms[ii].id for ii in range(4)])
    order = np.argsort(ids)
    forces = forces[order]
    np.testing.assert_allclose(forces, expected_f, atol=1e-8, rtol=0)

    idx_map = lammps.lmp.numpy.extract_atom("id")[: coord.shape[0]] - 1
    np.testing.assert_allclose(
        np.array(lammps.variables["eatom"].value),
        expected_ae[idx_map],
        atol=1e-8,
        rtol=1e-8,
    )

    vol = box[1] * box[3] * box[5]
    for ii in range(6):
        jj = [0, 4, 8, 3, 6, 7, 1, 2, 5][ii]
        pressure_jj = np.array(lammps.variables[f"pressure{jj}"].value) / (
            constants.nktv2p
        )
        expected_pressure_jj = -expected_v[idx_map, jj].sum(axis=0) / vol
        np.testing.assert_allclose(
            pressure_jj, expected_pressure_jj, atol=1e-8, rtol=1e-8
        )
    for ii in range(9):
        jj = [0, 4, 8, 3, 6, 7, 1, 2, 5][ii]
        virial_jj = np.array(lammps.variables[f"virial{jj}"].value) / (constants.nktv2p)
        np.testing.assert_allclose(
            virial_jj, expected_v[idx_map, jj], atol=1e-8, rtol=1e-8
        )


# ---------------------------------------------------------------------------
# Multi-rank: the spin+ZBL graph .pt2 carries the nested with-comm artifact
# (which includes the SFPG reverse-accumulate + broadcast exchange, issue
# #5906), so a 2-rank run must REPRODUCE the 1-rank result (energy, force
# and force_mag) rather than fail fast.
# ---------------------------------------------------------------------------


def _run_mpi_subprocess(
    extra_args: list[str] | None = None,
    nprocs: int = 2,
    data_path: Path | None = None,
    processors: str | None = None,
    capture: bool = False,
    timeout: float | None = None,
) -> dict:
    """Invoke the graph-spin MPI runner under ``mpirun -n <nprocs>`` against
    the spin+ZBL DPA4 graph ``.pt2``.

    Copied (module-global closure, not imported) from
    ``test_lammps_dpa4_spin_graph_pt2.py``'s twin. With ``capture=True``,
    return raw subprocess info (``returncode``, ``stdout``, ``stderr``,
    ``timed_out``); every invocation is bounded by ``timeout`` (default
    ``_MPI_DEFAULT_TIMEOUT``) so a should-fail-but-doesn't run cannot hang
    the suite, and on expiry the WHOLE mpirun process group is SIGKILLed.
    """
    if data_path is None:
        data_path = data_file
    if timeout is None:
        timeout = _MPI_DEFAULT_TIMEOUT
    with tempfile.NamedTemporaryFile(mode="r", suffix=".out", delete=False) as f:
        out_path = f.name
    try:
        argv = [
            "mpirun",
            "-n",
            str(nprocs),
            sys.executable,
            str(mpi_runner),
            str(data_path.resolve()),
            str(pb_file.resolve()),
            out_path,
        ]
        if processors is not None:
            argv.extend(["--processors", processors])
        elif nprocs == 1:
            argv.extend(["--processors", "1 1 1"])
        if extra_args:
            argv.extend(extra_args)
        proc = sp.Popen(
            argv,
            stdout=sp.PIPE if capture else None,
            stderr=sp.PIPE if capture else None,
            text=True,
            start_new_session=True,
        )
        try:
            stdout, stderr = proc.communicate(timeout=timeout)
        except sp.TimeoutExpired:
            os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            stdout, stderr = proc.communicate()
            if capture:
                return {
                    "returncode": None,
                    "stdout": stdout or "",
                    "stderr": stderr or "",
                    "timed_out": True,
                }
            raise RuntimeError(
                f"mpirun timed out after {timeout}s (process group killed); "
                "a should-succeed MPI regression is deadlocked."
            ) from None
        if capture:
            return {
                "returncode": proc.returncode,
                "stdout": stdout,
                "stderr": stderr,
                "timed_out": False,
            }
        if proc.returncode != 0:
            raise sp.CalledProcessError(proc.returncode, argv)
        with open(out_path) as fh:
            lines = fh.read().strip().splitlines()
        pe = float(lines[0])
        rows = np.array(
            [list(map(float, line.split())) for line in lines[1:]],
            dtype=np.float64,
        )
        return {"pe": pe, "rows": rows}
    finally:
        if os.path.exists(out_path):
            os.remove(out_path)


def _assert_mpi_matches_single_rank(single: dict, multi: dict) -> None:
    """Compare a 2-rank MPI result against the 1-rank one: pe, per-atom
    force and per-atom force_mag, all at rtol=atol=1e-10 (the sibling's MPI
    tolerances).  Both runs report LAMMPS's own ``fm`` (already scaled by
    ``spin_norm / _HBAR_METAL`` inside pair_deepspin.cpp), so the scaling
    cancels and the rows compare directly.
    """
    # anti-vacuity: a degenerate fixture (all-zero forces) would make the
    # comparison pass for the wrong reason.
    assert np.abs(multi["rows"][:, :3]).max() > 1e-6, "forces are trivially zero"
    assert np.abs(multi["rows"][:, 3:6]).max() > 1e-6, "force_mag is trivially zero"

    np.testing.assert_allclose(
        multi["pe"], single["pe"], rtol=1e-10, atol=1e-10, err_msg="energy"
    )
    np.testing.assert_allclose(
        multi["rows"][:, :3],
        single["rows"][:, :3],
        rtol=1e-10,
        atol=1e-10,
        err_msg="force",
    )
    np.testing.assert_allclose(
        multi["rows"][:, 3:6],
        single["rows"][:, 3:6],
        rtol=1e-10,
        atol=1e-10,
        err_msg="force_mag",
    )


@pytest.mark.skipif(
    shutil.which("mpirun") is None, reason="MPI is not installed on this system"
)
@pytest.mark.skipif(
    importlib.util.find_spec("mpi4py") is None, reason="mpi4py is not installed"
)
def test_pair_deepspin_mpi_matches_single_rank() -> None:
    """A 2-rank MPI run must reproduce the 1-rank result on the SAME archive.

    The spin+ZBL DPA4 graph ``.pt2`` carries the nested with-comm artifact,
    so ``DeepSpinPTExpt::compute_inner`` drives a real domain-decomposed run
    through ``run_model_graph_with_comm``: the per-block ghost FEATURE
    refresh (including the SFPG partials exchange) rides ``border_op`` /
    ``border_op_backward`` while ghost SPINS arrive via the LAMMPS ``sp``
    forward-comm.  Both the conservative force and the MAGNETIC force must
    be rank-count invariant.

    With this (unshifted) geometry the close Ni-Ni pair sits entirely on
    one rank's subdomain, so this test pins the baseline multi-rank route;
    the boundary-straddling bridging-zone pair is exercised by
    ``test_pair_deepspin_mpi_close_pair_across_ranks`` below.
    """
    single = _run_mpi_subprocess(nprocs=1, processors="1 1 1")
    multi = _run_mpi_subprocess(nprocs=2, processors="2 1 1")
    _assert_mpi_matches_single_rank(single, multi)


@pytest.mark.skipif(
    shutil.which("mpirun") is None, reason="MPI is not installed on this system"
)
@pytest.mark.skipif(
    importlib.util.find_spec("mpi4py") is None, reason="mpi4py is not installed"
)
def test_pair_deepspin_mpi_close_pair_across_ranks() -> None:
    """2-rank vs 1-rank parity with the bridging-zone Ni-Ni pair straddling
    the rank boundary.

    The shifted geometry places the ~0.978 A Ni-Ni pair at x = 6.93 / 6.19,
    on OPPOSITE sides of the ``processors 2 1 1`` boundary at lx/2 = 6.5,
    and 0.8 < 0.978 < 1.2 puts the pair inside the bridging transition zone
    -- so each rank's per-node ``[log_eta, zero_count]`` SFPG partial for
    the pair is rank-incomplete and correctness depends on the
    reverse-accumulate + broadcast exchange inside the with-comm artifact
    (issue #5906).
    """
    # Static straddle guard: the two Ni atoms must sit on opposite sides of
    # the lx/2 boundary.  Without this the SFPG-exchange parity below is
    # vacuous (the whole bridging-zone pair would be owned by one rank and
    # the cross-rank completion would never be exercised).
    half_lx = box[1] / 2.0
    x_lo, x_hi = sorted(coord_close_pair[:2, 0])
    assert x_lo < half_lx < x_hi, (
        f"close-pair geometry no longer straddles the processors 2 1 1 "
        f"boundary: Ni x = {x_lo}, {x_hi}, lx/2 = {half_lx}"
    )

    single = _run_mpi_subprocess(
        nprocs=1, processors="1 1 1", data_path=data_file_close_pair
    )
    multi = _run_mpi_subprocess(
        nprocs=2, processors="2 1 1", data_path=data_file_close_pair
    )
    _assert_mpi_matches_single_rank(single, multi)
