# SPDX-License-Identifier: LGPL-3.0-or-later
"""LAMMPS ``pair_style deepspin`` on the COMBINED native-spin + ZBL-bridged
DPA4 NeighborGraph (graph-schema) ``.pt2``
(``deeppot_dpa4_spin_zbl_graph.pt2``, generated by
``source/tests/infer/gen_dpa4_spin_zbl.py``).

This pins the spin+ZBL variant end-to-end, which previously had NO LAMMPS
coverage at all: single-rank pair/virial against a LIVE ``DeepPot`` reference
computed at test-setup time on this module's own geometry, AND 2-rank vs
1-rank MPI parity -- including a close-pair geometry whose ~0.978 A Ni-Ni
pair straddles the ``processors 2 1 1`` domain boundary INSIDE the bridging
transition zone (the generator sets ``bridging_r_inner = 0.8`` /
``bridging_r_outer = 1.2``, verbatim from ``gen_dpa4_zbl.py``; 0.8 < 0.978 <
1.2).  Bridging enables the descriptor's Source Freeze Propagation Gate,
whose per-node ``[log_eta, zero_count]`` partials fold a node's FULL
outgoing-edge set; edges exist only for owned centres, so the partials are
rank-incomplete.  The SFPG cross-rank completion -- one reverse-accumulate
(``border_op_backward``) + forward-broadcast (``border_op``) exchange of the
per-node partials inside the with-comm artifact -- completes them before the
gate is applied, which is what makes bridged models multi-rank capable
(issue #5906).  The close-pair test is the geometry that actually exercises
that exchange: without a bridging-zone pair split across ranks the parity
comparison would be vacuous.

Reference (energy / force / force_mag / virial) values are computed LIVE at
test-setup time via ``deepmd.infer.DeepPot.eval`` on the archive for the
fixed 4-atom NiO system reused from ``test_lammps_dpa4_spin_graph_pt2.py``
(box 13x13x13, 2 spin-active Ni + 2 non-magnetic O) -- deliberately NOT
hardcoded (a hardcoded reference goes stale the moment DPA4 numerics shift)
and NOT read from the generator's ``.expected`` sidecar (its own 6-atom
system sits in a 6x6x6 box whose edge exactly equals DPA4's ghost cutoff --
not a safe geometry for a LAMMPS periodic run).  ``dpa4_spin_harness.compute_expected`` runs
in a subprocess so importing ``deepmd``'s Python package does not share a
process with the LAMMPS plugin's own loaded ``libdeepmd_op_pt.so`` (see
``test_lammps_model_devi_pt2.py``).
"""

import importlib.util
import os
import shutil
from pathlib import (
    Path,
)

import numpy as np
import pytest
from dpa4_spin_harness import (
    BOX,
    COORD,
    SPIN,
    TYPE_NIO,
    assert_mpi_matches_single_rank,
    check_single_rank_energy_force,
    check_single_rank_virial,
    compute_expected,
    make_lammps,
    run_mpi_spin_runner,
)
from write_lmp_data import (
    write_lmp_data_spin,
)

pb_file = (
    Path(__file__).parent.parent.parent
    / "tests"
    / "infer"
    / "deeppot_dpa4_spin_zbl_graph.pt2"
)
data_file = Path(__file__).parent / "data_dpa4_spin_zbl_pt2.lmp"
data_file_close_pair = Path(__file__).parent / "data_dpa4_spin_zbl_close_pair_pt2.lmp"
# The MPI runner is graph-spin-specific (no aparam / no NULL-type extras,
# unlike run_mpi_pair_deepmd_spin_dpa3_pt2.py's virtual-atom-scheme runner):
# the native-spin (+ZBL) DPA4 fixtures take no fparam/aparam, so the plain
# native-spin runner is reused verbatim -- only the archive differs.
mpi_runner = Path(__file__).parent / "run_mpi_pair_deepmd_spin_graph_dpa4_pt2.py"

# The shared 4-atom NiO system (dpa4_spin_harness): the Ni-Ni pair (atoms 0
# and 1) sits ~0.978 A apart -- inside this variant's bridging transition
# zone (0.8, 1.2), so the ZBL channel is active even in the single-rank
# tests.
box, coord, spin, type_NiO = BOX, COORD, SPIN, TYPE_NIO

# Close-pair geometry for the MPI-parity test: the SAME 4-atom system
# shifted along x by -5.9, so the ~0.978 A Ni-Ni pair lands at x = 6.93 /
# 6.19 -- straddling the lx/2 = 6.5 domain boundary of ``processors 2 1 1``.
# The shift pushes atom 2 (x = 3.51) below zero, so the x column is wrapped
# back into the periodic box with ``np.mod(x, 13)`` (LAMMPS is periodic, so
# wrapping changes nothing physically; it just keeps the data file's
# coordinates inside [0, lx) as write_lmp_data_spin expects).
_CLOSE_PAIR_SHIFT_X = -5.9
coord_close_pair = coord.copy()
coord_close_pair[:, 0] = np.mod(coord[:, 0] + _CLOSE_PAIR_SHIFT_X, box[1])

# Reference values, populated by ``compute_expected`` in ``setup_module`` --
# see the module docstring for why these are computed live via a DeepPot
# subprocess call rather than hardcoded or read from a sidecar file.
expected: dict = {}


def setup_module() -> None:
    if os.environ.get("ENABLE_PYTORCH", "1") != "1":
        pytest.skip(
            "Skip test because PyTorch support is not enabled.",
        )
    if not pb_file.exists():
        pytest.skip("deeppot_dpa4_spin_zbl_graph.pt2 not found")
    expected.update(compute_expected(pb_file))
    write_lmp_data_spin(box, coord, spin, type_NiO, data_file)
    write_lmp_data_spin(box, coord_close_pair, spin, type_NiO, data_file_close_pair)


def teardown_module() -> None:
    for path in (data_file, data_file_close_pair):
        if path.exists():
            os.remove(path)


@pytest.fixture
def lammps():
    lmp = make_lammps(data_file)
    yield lmp
    lmp.close()


def test_pair_deepspin(lammps) -> None:
    """Single-rank LAMMPS energy + force + force_mag vs the Python DeepEval
    reference on the spin+ZBL archive.

    The shared check also pins force_mag == 0 on the two non-spin (O)
    atoms: the analytical ZBL child, which knows nothing about spin, must
    not leak into that channel.
    """
    check_single_rank_energy_force(lammps, pb_file, expected)


def test_pair_deepspin_virial(lammps) -> None:
    """Single-rank per-atom pe/pressure/virial on the spin+ZBL archive."""
    check_single_rank_virial(lammps, pb_file, expected)


# ---------------------------------------------------------------------------
# Multi-rank: the spin+ZBL graph .pt2 carries the nested with-comm artifact
# (which includes the SFPG reverse-accumulate + broadcast exchange, issue
# #5906), so a 2-rank run must REPRODUCE the 1-rank result (energy, force
# and force_mag) rather than fail fast.
# ---------------------------------------------------------------------------


def _run_mpi(data_path: Path, nprocs: int, processors: str) -> dict:
    """This module's binding of the shared runner (archive + runner fixed)."""
    return run_mpi_spin_runner(
        mpi_runner, pb_file, data_path, nprocs=nprocs, processors=processors
    )


@pytest.mark.skipif(
    shutil.which("mpirun") is None, reason="MPI is not installed on this system"
)
@pytest.mark.skipif(
    importlib.util.find_spec("mpi4py") is None, reason="mpi4py is not installed"
)
def test_pair_deepspin_mpi_matches_single_rank() -> None:
    """A 2-rank MPI run must reproduce the 1-rank result on the SAME archive.

    The spin+ZBL DPA4 graph ``.pt2`` carries the nested with-comm artifact,
    so ``DeepSpinPTExpt::compute_inner`` drives a real domain-decomposed run
    through ``run_model_graph_with_comm``: the per-block ghost FEATURE
    refresh (including the SFPG partials exchange) rides ``border_op`` /
    ``border_op_backward`` while ghost SPINS arrive via the LAMMPS ``sp``
    forward-comm.  Both the conservative force and the MAGNETIC force must
    be rank-count invariant.

    With this (unshifted) geometry the close Ni-Ni pair sits entirely on
    one rank's subdomain, so this test pins the baseline multi-rank route;
    the boundary-straddling bridging-zone pair is exercised by
    ``test_pair_deepspin_mpi_close_pair_across_ranks`` below.
    """
    single = _run_mpi(data_file, 1, "1 1 1")
    multi = _run_mpi(data_file, 2, "2 1 1")
    assert_mpi_matches_single_rank(single, multi)


@pytest.mark.skipif(
    shutil.which("mpirun") is None, reason="MPI is not installed on this system"
)
@pytest.mark.skipif(
    importlib.util.find_spec("mpi4py") is None, reason="mpi4py is not installed"
)
def test_pair_deepspin_mpi_close_pair_across_ranks() -> None:
    """2-rank vs 1-rank parity with the bridging-zone Ni-Ni pair straddling
    the rank boundary.

    The shifted geometry places the ~0.978 A Ni-Ni pair at x = 6.93 / 6.19,
    on OPPOSITE sides of the ``processors 2 1 1`` boundary at lx/2 = 6.5,
    and 0.8 < 0.978 < 1.2 puts the pair inside the bridging transition zone
    -- so each rank's per-node ``[log_eta, zero_count]`` SFPG partial for
    the pair is rank-incomplete and correctness depends on the
    reverse-accumulate + broadcast exchange inside the with-comm artifact
    (issue #5906).
    """
    # Static straddle guard: the two Ni atoms must sit on opposite sides of
    # the lx/2 boundary.  Without this the SFPG-exchange parity below is
    # vacuous (the whole bridging-zone pair would be owned by one rank and
    # the cross-rank completion would never be exercised).
    half_lx = box[1] / 2.0
    x_lo, x_hi = sorted(coord_close_pair[:2, 0])
    assert x_lo < half_lx < x_hi, (
        f"close-pair geometry no longer straddles the processors 2 1 1 "
        f"boundary: Ni x = {x_lo}, {x_hi}, lx/2 = {half_lx}"
    )

    single = _run_mpi(data_file_close_pair, 1, "1 1 1")
    multi = _run_mpi(data_file_close_pair, 2, "2 1 1")
    assert_mpi_matches_single_rank(single, multi)
