# SPDX-License-Identifier: LGPL-3.0-or-later
"""Test the LAMMPS ``charge_spin`` pair_style keyword (.pt2 DPA3 model).

Exercises the parsing and wiring of the ``charge_spin`` keyword through to the
backend: the model (chg_spin.pt2, DPA3 with add_chg_spin_ebd=True and
default_chg_spin=[0.0, 1.0]) is generated by source/tests/infer/gen_chg_spin.py,
together with the reference values in chg_spin.expected.
"""

import os
from pathlib import (
    Path,
)

import numpy as np
import pytest
from expected_ref import (
    read_expected_ref,
)
from lammps import (
    PyLammps,
)
from write_lmp_data import (
    write_lmp_data,
)

pt2_file = Path(__file__).parent.parent.parent / "tests" / "infer" / "chg_spin.pt2"
ref_file = Path(__file__).parent.parent.parent / "tests" / "infer" / "chg_spin.expected"
data_file = Path(__file__).parent / "data_chg_spin_pt2.lmp"

# Reference values written by source/tests/infer/gen_chg_spin.py (PBC case):
#   "default"  -- no charge_spin keyword -> stored default_chg_spin [0.0, 1.0]
#   "explicit" -- charge_spin 1.0 2.0
# Guarded with try/except because gen_chg_spin.py only runs when PyTorch is
# built; matrices that disable PyTorch still load this file at collection time.
try:
    _ref = read_expected_ref(ref_file)
    expected_e_default = float(np.sum(_ref["default"]["expected_e"]))
    expected_f_default = _ref["default"]["expected_f"].reshape(6, 3)
    expected_e_explicit = float(np.sum(_ref["explicit"]["expected_e"]))
    expected_f_explicit = _ref["explicit"]["expected_f"].reshape(6, 3)
except FileNotFoundError:
    expected_e_default = expected_f_default = None
    expected_e_explicit = expected_f_explicit = None

box = np.array([0, 13, 0, 13, 0, 13, 0, 0, 0])
coord = np.array(
    [
        [12.83, 2.56, 2.18],
        [12.09, 2.87, 2.74],
        [0.25, 3.32, 1.68],
        [3.36, 3.00, 1.81],
        [3.51, 2.51, 2.60],
        [4.27, 3.22, 1.56],
    ]
)
# atype [0, 1, 1, 0, 1, 1] (O, H, H, O, H, H) -> LAMMPS types [1, 2, 2, 1, 2, 2]
type_OH = np.array([1, 2, 2, 1, 2, 2])


def setup_module() -> None:
    if os.environ.get("ENABLE_PYTORCH", "1") != "1":
        pytest.skip("Skip test because PyTorch support is not enabled.")
    write_lmp_data(box, coord, type_OH, data_file)


def teardown_module() -> None:
    if data_file.exists():
        os.remove(data_file)


def _lammps(data_file, units="metal") -> PyLammps:
    lammps = PyLammps()
    lammps.units(units)
    lammps.boundary("p p p")
    lammps.atom_style("atomic")
    # DPA3 (message passing) resolves ghost atoms via the LAMMPS atom-map.
    lammps.atom_modify("map yes")
    lammps.neighbor("2.0 bin")
    lammps.neigh_modify("every 10 delay 0 check no")
    lammps.read_data(data_file.resolve())
    lammps.mass("1 16")
    lammps.mass("2 2")
    lammps.timestep(0.0005)
    lammps.fix("1 all nve")
    return lammps


@pytest.fixture
def lammps():
    if not pt2_file.is_file():
        pytest.skip(f"Skip because {pt2_file} was not generated.")
    lmp = _lammps(data_file=data_file)
    yield lmp
    lmp.close()


def test_pair_deepmd_charge_spin_default(lammps) -> None:
    """No charge_spin keyword -> the model's stored default_chg_spin is used."""
    lammps.pair_style(f"deepmd {pt2_file.resolve()}")
    lammps.pair_coeff("* *")
    lammps.run(0)
    assert lammps.eval("pe") == pytest.approx(expected_e_default)
    for ii in range(6):
        assert lammps.atoms[ii].force == pytest.approx(
            expected_f_default[lammps.atoms[ii].id - 1]
        )
    lammps.run(1)


def test_pair_deepmd_charge_spin_explicit(lammps) -> None:
    """Explicit ``charge_spin`` keyword is parsed and threaded to the model."""
    lammps.pair_style(f"deepmd {pt2_file.resolve()} charge_spin 1.0 2.0")
    lammps.pair_coeff("* *")
    lammps.run(0)
    assert lammps.eval("pe") == pytest.approx(expected_e_explicit)
    for ii in range(6):
        assert lammps.atoms[ii].force == pytest.approx(
            expected_f_explicit[lammps.atoms[ii].id - 1]
        )
    lammps.run(1)


def test_charge_spin_changes_result(lammps) -> None:
    """Different charge_spin must give a different energy (keyword takes effect)."""
    lammps.pair_style(f"deepmd {pt2_file.resolve()} charge_spin 1.0 2.0")
    lammps.pair_coeff("* *")
    lammps.run(0)
    assert lammps.eval("pe") != pytest.approx(expected_e_default)
