# SPDX-License-Identifier: LGPL-3.0-or-later
"""Multi-rank LAMMPS test for the DPA3 spin GNN .pt2 fixture.

The DPA3 spin .pt2 (``deeppot_dpa3_spin_mpi.pt2``) is generated by
``source/tests/infer/gen_spin.py`` with ``use_loc_mapping=False``,
producing a dual-artifact archive whose nested
``forward_lower_with_comm.pt2`` is selected by ``DeepSpinPTExpt`` when
LAMMPS reports ``nswap > 0`` (multi-rank). This test exercises the
spin GNN multi-rank dispatch end-to-end:

1. Eager parity is already covered by
   ``source/tests/pt_expt/model/test_spin_export_with_comm.py
   ::test_spin_dpa3_eager_parity`` (Python override only).
2. AOTI compile of the with-comm artifact is verified at fixture
   generation time (``gen_spin.py`` calls ``convert_backend`` which
   triggers the compile).
3. **This test** wires the loaded artifact through ``DeepSpinPTExpt``,
   ``commPTExpt::build_comm_tensors_positional``, the C++
   ``deepmd_export::border_op`` registration, and real MPI ghost
   exchange between two LAMMPS subdomains. A passing test means the
   full chain (Python override + AOTI export + C++ load + comm-tensor
   build + custom op invocation + MPI exchange) produces forces /
   force_mag / virial identical to a same-archive single-rank
   reference within numerical tolerance.

Compares mpi-2 vs same-archive mpi-1 to avoid hardcoding numerical
references (the same approach used for the DPA3 / DPA2 multi-rank
tests). Same-archive means the regular and with-comm artifacts come
from the same trace, so any divergence is purely the multi-rank
dispatch path's responsibility.
"""

from __future__ import (
    annotations,
)

import importlib.util
import os
import shutil
import subprocess as sp
import sys
import tempfile
from pathlib import (
    Path,
)

import numpy as np
import pytest
from write_lmp_data import (
    write_lmp_data_spin,
)

pb_file_mpi = (
    Path(__file__).parent.parent.parent
    / "tests"
    / "infer"
    / "deeppot_dpa3_spin_mpi.pt2"
)
data_file = Path(__file__).parent / "data_dpa3_spin_pt2.lmp"
# Elongated-box fixture for the spin empty-subdomain MPI test: x is
# extended to 30 A while atoms remain in x in [3, 13]. Combined with
# ``processors 2 1 1`` this leaves rank 1 (x >= 15) with zero local
# atoms, exercising the ``copy_from_nlist`` empty-rank guard for spin.
data_file_empty_subdomain = (
    Path(__file__).parent / "data_dpa3_spin_pt2_empty_subdomain.lmp"
)
# NULL-type fixture: 4 real Ni-O atoms + 2 LAMMPS type-3 atoms
# straddling the x=6.5 rank boundary. With ``pair_coeff * * Ni O NULL``
# LAMMPS type 3 maps to deepmd atype=-1, so those atoms are filtered
# by ``select_real_atoms_coord`` and the comm tensors must be remapped
# via ``fwd_map`` before being handed to the with-comm artifact.
# Forces / force_mag on the 4 real atoms must match the no-NULL
# baseline (mpi-1 reference run); NULL atoms get zero forces from the
# deepmd model.
data_file_null_type = Path(__file__).parent / "data_dpa3_spin_pt2_null_type.lmp"

# 4-atom Ni-O system; same layout as ``test_lammps_spin_pt2.py``. With
# ``processors 2 1 1`` the split sits at x=6.5 -> 2 atoms per rank.
box = np.array([0, 13, 0, 13, 0, 13, 0, 0, 0])
coord = np.array(
    [
        [12.83, 2.56, 2.18],
        [12.09, 2.87, 2.74],
        [3.51, 2.51, 2.60],
        [4.27, 3.22, 1.56],
    ]
)
spin = np.array(
    [
        [0, 0, 1.2737],
        [0, 0, 1.2737],
        [0, 0, 0],
        [0, 0, 0],
    ]
)
type_NiO = np.array([1, 1, 2, 2])


def setup_module() -> None:
    if os.environ.get("ENABLE_PYTORCH", "1") != "1":
        pytest.skip(
            "Skip test because PyTorch support is not enabled.",
        )
    write_lmp_data_spin(box, coord, spin, type_NiO, data_file)
    # Elongated x-axis; atoms unchanged. ``processors 2 1 1`` splits
    # at x=15 A and rank 1 owns x >= 15, which is empty.
    box_empty = np.array([0, 30, 0, 13, 0, 13, 0, 0, 0])
    write_lmp_data_spin(box_empty, coord, spin, type_NiO, data_file_empty_subdomain)
    # NULL-type fixture: append 2 LAMMPS type-3 atoms within rcut
    # (~4 A) of real atoms on BOTH sides of the x=6.5 rank boundary,
    # so they appear in cross-rank sendlists and the fwd_map-based
    # comm-tensor remap is genuinely exercised. NULL atoms still need
    # spin coordinates (write_lmp_data_spin format); we give them
    # zero spin like the type-2 (O) atoms.
    coord_null = np.concatenate(
        [
            coord,
            np.array(
                [
                    [5.5, 6.0, 6.0],  # rank 0 side, near boundary
                    [7.5, 7.0, 7.0],  # rank 1 side, near boundary
                ]
            ),
        ]
    )
    spin_null = np.concatenate([spin, np.zeros((2, 3))])
    type_null = np.concatenate([type_NiO, np.array([3, 3])])
    write_lmp_data_spin(box, coord_null, spin_null, type_null, data_file_null_type)


def teardown_module() -> None:
    for f in [data_file, data_file_empty_subdomain, data_file_null_type]:
        if f.exists():
            os.remove(f)


def _run_mpi_subprocess(
    nprocs: int,
    extra_args: list[str] | None = None,
    processors: str | None = None,
    data_path: Path | None = None,
    runner_args: list[str] | None = None,
) -> dict:
    """Run ``run_mpi_pair_deepmd_spin_dpa3_pt2.py`` under
    ``mpirun -n <nprocs>`` and return
    ``{"pe", "forces", "force_mag", "virials"}``.

    ``data_path`` (default ``data_file``) selects the LAMMPS data file
    -- the empty-subdomain and NULL-type tests point at non-default
    fixtures. ``runner_args`` flows additional flags (e.g.
    ``--pair-coeff``, ``--mass3``) to the subprocess runner.
    """
    if data_path is None:
        data_path = data_file
    with tempfile.NamedTemporaryFile(mode="r", suffix=".out", delete=False) as f:
        out_path = f.name
    try:
        argv = [
            "mpirun",
            "-n",
            str(nprocs),
            sys.executable,
            str(Path(__file__).parent / "run_mpi_pair_deepmd_spin_dpa3_pt2.py"),
            str(data_path.resolve()),
            str(pb_file_mpi.resolve()),
            out_path,
        ]
        if processors is not None:
            argv.extend(["--processors", processors])
        elif nprocs == 1:
            argv.extend(["--processors", "1 1 1"])
        if extra_args:
            argv.extend(extra_args)
        if runner_args:
            argv.extend(runner_args)
        sp.check_call(argv)
        with open(out_path) as fh:
            lines = fh.read().strip().splitlines()
        pe = float(lines[0])
        rows = np.array(
            [list(map(float, line.split())) for line in lines[1:]],
            dtype=np.float64,
        )
        # Each row: 3 force + 3 force_mag + 9 virial = 15 cols (see runner).
        forces = rows[:, :3]
        force_mag = rows[:, 3:6]
        virials = rows[:, 6:]
        return {
            "pe": pe,
            "forces": forces,
            "force_mag": force_mag,
            "virials": virials,
        }
    finally:
        if os.path.exists(out_path):
            os.remove(out_path)


@pytest.mark.skipif(
    shutil.which("mpirun") is None, reason="MPI is not installed on this system"
)
@pytest.mark.skipif(
    importlib.util.find_spec("mpi4py") is None, reason="mpi4py is not installed"
)
def test_pair_deepmd_mpi_dpa3_spin() -> None:
    """Multi-rank LAMMPS run for spin DPA3 .pt2 must match the
    same-archive single-rank reference within numerical tolerance for
    energy, forces, force_mag, and per-atom virial.

    Going via mpi-1 (rather than a hardcoded reference array) means we
    are validating the multi-rank dispatch path itself, isolated from
    any tracing / AOTI precision drift that might appear at fixture
    generation time. Single-rank uses the regular artifact (nswap=0);
    multi-rank uses the with-comm artifact — so a divergence here is
    necessarily a problem in either ``DeepSpinPTExpt`` multi-rank
    dispatch, the spin branch of ``_exchange_ghosts``, the C++
    ``deepmd_export::border_op`` invocation, or the comm-tensor
    builder.
    """
    out_mpi = _run_mpi_subprocess(nprocs=2)
    out_ref = _run_mpi_subprocess(nprocs=1)

    assert out_mpi["pe"] == pytest.approx(out_ref["pe"], rel=1e-10, abs=1e-12)
    np.testing.assert_allclose(out_mpi["forces"], out_ref["forces"], atol=1e-8, rtol=0)
    np.testing.assert_allclose(
        out_mpi["force_mag"], out_ref["force_mag"], atol=1e-8, rtol=0
    )
    np.testing.assert_allclose(
        out_mpi["virials"], out_ref["virials"], atol=1e-8, rtol=0
    )


@pytest.mark.skipif(
    shutil.which("mpirun") is None, reason="MPI is not installed on this system"
)
@pytest.mark.skipif(
    importlib.util.find_spec("mpi4py") is None, reason="mpi4py is not installed"
)
def test_pair_deepmd_mpi_dpa3_spin_empty_subdomain() -> None:
    """Spin DPA3 multi-rank with one empty rank.

    Elongated x box (30 A) + ``processors 2 1 1`` puts all 4 atoms on
    rank 0; rank 1 has nloc=0. Exercises the C++ ``copy_from_nlist``
    empty-rank guard for the spin path (the with-comm artifact still
    runs on rank 1 with nloc_real=0). Compares against same-archive
    mpi-1 reference.
    """
    out_mpi = _run_mpi_subprocess(nprocs=2, data_path=data_file_empty_subdomain)
    out_ref = _run_mpi_subprocess(nprocs=1, data_path=data_file_empty_subdomain)

    assert out_mpi["pe"] == pytest.approx(out_ref["pe"], rel=1e-10, abs=1e-12)
    np.testing.assert_allclose(out_mpi["forces"], out_ref["forces"], atol=1e-8, rtol=0)
    np.testing.assert_allclose(
        out_mpi["force_mag"], out_ref["force_mag"], atol=1e-8, rtol=0
    )
    np.testing.assert_allclose(
        out_mpi["virials"], out_ref["virials"], atol=1e-8, rtol=0
    )


@pytest.mark.skipif(
    shutil.which("mpirun") is None, reason="MPI is not installed on this system"
)
@pytest.mark.skipif(
    importlib.util.find_spec("mpi4py") is None, reason="mpi4py is not installed"
)
def test_pair_deepmd_mpi_dpa3_spin_null_type() -> None:
    """Spin DPA3 multi-rank with NULL-type atoms straddling the
    rank boundary.

    Two LAMMPS type-3 atoms (mapped to deepmd atype=-1 via
    ``pair_coeff * * Ni O NULL``) sit at x=5.5 and x=7.5, just inside
    the rcut window of either side of the x=6.5 boundary. They appear
    in the cross-rank sendlists and are filtered by
    ``select_real_atoms_coord`` -- so the spin path goes through
    ``DeepSpinPTExpt::compute`` with ``nall_real < nall``, triggering
    the ``has_null_atoms`` branch that calls
    ``build_comm_tensors_positional_with_virtual_atoms`` (fwd_map-based
    sendlist remap). Compares mpi-2 vs same-archive mpi-1 reference
    (nullifying NULL forces and using the same fwd_map remap on rank 0
    too).
    """
    runner_args = ["--pair-coeff", "* * Ni O NULL", "--mass3", "1.0"]
    out_mpi = _run_mpi_subprocess(
        nprocs=2, data_path=data_file_null_type, runner_args=runner_args
    )
    out_ref = _run_mpi_subprocess(
        nprocs=1, data_path=data_file_null_type, runner_args=runner_args
    )

    assert out_mpi["pe"] == pytest.approx(out_ref["pe"], rel=1e-10, abs=1e-12)
    np.testing.assert_allclose(out_mpi["forces"], out_ref["forces"], atol=1e-8, rtol=0)
    np.testing.assert_allclose(
        out_mpi["force_mag"], out_ref["force_mag"], atol=1e-8, rtol=0
    )
    np.testing.assert_allclose(
        out_mpi["virials"], out_ref["virials"], atol=1e-8, rtol=0
    )
    # Sanity: NULL atoms (ids 5, 6) get exactly zero forces from the
    # deepmd model. ``write_lmp_data_spin`` writes atoms in the order
    # given (id 1..N), so type-3 NULL atoms are ids 5, 6 (after the 4
    # real Ni-O atoms).
    np.testing.assert_array_equal(out_mpi["forces"][4:], np.zeros((2, 3)))
    np.testing.assert_array_equal(out_mpi["force_mag"][4:], np.zeros((2, 3)))
