// SPDX-License-Identifier: LGPL-3.0-or-later
// Test C++ inference for pt_expt (.pt2) backend with charge_spin input (DPA3).
// Model generated by source/tests/infer/gen_chg_spin.py.
#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <vector>

#include "DeepPot.h"
#include "DeepPotPTExpt.h"
#include "expected_ref.h"
#include "neighbor_list.h"
#include "test_utils.h"

#undef EPSILON
#define EPSILON (std::is_same<VALUETYPE, double>::value ? 1e-7 : 1e-4)

namespace {
constexpr const char* kRefPath = "../../tests/infer/chg_spin.expected";
constexpr const char* kModelPath = "../../tests/infer/chg_spin.pt2";
}  // namespace

template <class VALUETYPE>
class TestInferDeepPotChgSpinPtExpt : public ::testing::Test {
 protected:
  std::vector<VALUETYPE> coord = {12.83, 2.56, 2.18, 12.09, 2.87, 2.74,
                                  00.25, 3.32, 1.68, 3.36,  3.00, 1.81,
                                  3.51,  2.51, 2.60, 4.27,  3.22, 1.56};
  std::vector<int> atype = {0, 1, 1, 0, 1, 1};
  std::vector<VALUETYPE> box = {13., 0., 0., 0., 13., 0., 0., 0., 13.};
  // charge_spin is always double regardless of VALUETYPE.
  // [1.0, 2.0] maps to charge idx 101, spin idx 2 — both differ from the
  // model's default_chg_spin [0.0, 1.0] (charge idx 100, spin idx 1).
  std::vector<double> charge_spin_explicit = {1.0, 2.0};

  std::vector<VALUETYPE> expected_e_explicit;
  std::vector<VALUETYPE> expected_f_explicit;
  std::vector<VALUETYPE> expected_v_explicit;
  std::vector<VALUETYPE> expected_e_default;
  std::vector<VALUETYPE> expected_f_default;
  std::vector<VALUETYPE> expected_v_default;
  int natoms;
  double expected_tot_e_explicit;
  double expected_tot_e_default;
  std::vector<VALUETYPE> expected_tot_v_explicit;
  std::vector<VALUETYPE> expected_tot_v_default;

  static deepmd::DeepPot dp;

  static void SetUpTestSuite() {
#if defined(BUILD_PYTORCH) && BUILD_PT_EXPT
    dp.init(kModelPath);
#endif
  }

  void SetUp() override {
#if !defined(BUILD_PYTORCH) || !BUILD_PT_EXPT
    GTEST_SKIP() << "Skip because PyTorch support is not enabled.";
#endif
    deepmd_test::ExpectedRef ref;
    ref.load(kRefPath);
    expected_e_explicit = ref.get<VALUETYPE>("explicit", "expected_e");
    expected_f_explicit = ref.get<VALUETYPE>("explicit", "expected_f");
    expected_v_explicit = ref.get<VALUETYPE>("explicit", "expected_v");
    expected_e_default = ref.get<VALUETYPE>("default", "expected_e");
    expected_f_default = ref.get<VALUETYPE>("default", "expected_f");
    expected_v_default = ref.get<VALUETYPE>("default", "expected_v");

    natoms = expected_e_explicit.size();
    EXPECT_EQ(natoms * 3, static_cast<int>(expected_f_explicit.size()));
    EXPECT_EQ(natoms * 9, static_cast<int>(expected_v_explicit.size()));
    EXPECT_EQ(natoms, static_cast<int>(expected_e_default.size()));

    expected_tot_e_explicit = 0.;
    expected_tot_e_default = 0.;
    expected_tot_v_explicit.assign(9, 0.);
    expected_tot_v_default.assign(9, 0.);
    for (int ii = 0; ii < natoms; ++ii) {
      expected_tot_e_explicit += expected_e_explicit[ii];
      expected_tot_e_default += expected_e_default[ii];
    }
    for (int ii = 0; ii < natoms; ++ii) {
      for (int dd = 0; dd < 9; ++dd) {
        expected_tot_v_explicit[dd] += expected_v_explicit[ii * 9 + dd];
        expected_tot_v_default[dd] += expected_v_default[ii * 9 + dd];
      }
    }
  }

  void TearDown() override {}

  static void TearDownTestSuite() { dp = deepmd::DeepPot(); }
};

template <class VALUETYPE>
deepmd::DeepPot TestInferDeepPotChgSpinPtExpt<VALUETYPE>::dp;

TYPED_TEST_SUITE(TestInferDeepPotChgSpinPtExpt, ValueTypes);

TYPED_TEST(TestInferDeepPotChgSpinPtExpt, dim_chg_spin) {
  deepmd::DeepPot& dp = this->dp;
  EXPECT_EQ(dp.dim_chg_spin(), 2);
}

TYPED_TEST(TestInferDeepPotChgSpinPtExpt, cpu_build_nlist_explicit) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<double>& charge_spin = this->charge_spin_explicit;
  std::vector<VALUETYPE>& expected_f = this->expected_f_explicit;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_explicit;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_explicit;
  deepmd::DeepPot& dp = this->dp;

  double ener;
  std::vector<VALUETYPE> force, virial;
  dp.compute(ener, force, virial, coord, atype, box, {}, {}, charge_spin);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepPotChgSpinPtExpt, cpu_build_nlist_default) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_f = this->expected_f_default;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_default;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_default;
  deepmd::DeepPot& dp = this->dp;

  double ener;
  std::vector<VALUETYPE> force, virial;
  // Empty charge_spin triggers default_chg_spin_ fallback ([0.0, 1.0])
  dp.compute(ener, force, virial, coord, atype, box);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepPotChgSpinPtExpt, cpu_lmp_nlist_explicit) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<double>& charge_spin = this->charge_spin_explicit;
  std::vector<VALUETYPE>& expected_f = this->expected_f_explicit;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_explicit;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_explicit;
  deepmd::DeepPot& dp = this->dp;

  float rc = dp.cutoff();
  int nloc = coord.size() / 3;
  std::vector<VALUETYPE> coord_cpy;
  std::vector<int> atype_cpy, mapping;
  std::vector<std::vector<int>> nlist_data;
  _build_nlist<VALUETYPE>(nlist_data, coord_cpy, atype_cpy, mapping, coord,
                          atype, box, rc);
  int nall = coord_cpy.size() / 3;
  std::vector<int> ilist(nloc), numneigh(nloc);
  std::vector<int*> firstneigh(nloc);
  deepmd::InputNlist inlist(nloc, &ilist[0], &numneigh[0], &firstneigh[0]);
  convert_nlist(inlist, nlist_data);
  // DPA3 repflows uses mapping; pass it so the C++ backend can
  // correctly map ghost atoms back to local atoms.
  inlist.mapping = mapping.data();

  double ener;
  std::vector<VALUETYPE> force_, virial;
  dp.compute(ener, force_, virial, coord_cpy, atype_cpy, box, nall - nloc,
             inlist, 0, {}, {}, charge_spin);
  std::vector<VALUETYPE> force;
  _fold_back<VALUETYPE>(force, force_, mapping, nloc, nall, 3);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }

  // Verify ago=1 (cached nlist) gives same result
  ener = 0.;
  std::fill(force_.begin(), force_.end(), 0.0);
  std::fill(virial.begin(), virial.end(), 0.0);
  dp.compute(ener, force_, virial, coord_cpy, atype_cpy, box, nall - nloc,
             inlist, 1, {}, {}, charge_spin);
  _fold_back<VALUETYPE>(force, force_, mapping, nloc, nall, 3);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepPotChgSpinPtExpt, cpu_lmp_nlist_default) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_f = this->expected_f_default;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_default;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_default;
  deepmd::DeepPot& dp = this->dp;

  float rc = dp.cutoff();
  int nloc = coord.size() / 3;
  std::vector<VALUETYPE> coord_cpy;
  std::vector<int> atype_cpy, mapping;
  std::vector<std::vector<int>> nlist_data;
  _build_nlist<VALUETYPE>(nlist_data, coord_cpy, atype_cpy, mapping, coord,
                          atype, box, rc);
  int nall = coord_cpy.size() / 3;
  std::vector<int> ilist(nloc), numneigh(nloc);
  std::vector<int*> firstneigh(nloc);
  deepmd::InputNlist inlist(nloc, &ilist[0], &numneigh[0], &firstneigh[0]);
  convert_nlist(inlist, nlist_data);
  // DPA3 repflows uses mapping; pass it so the C++ backend can
  // correctly map ghost atoms back to local atoms.
  inlist.mapping = mapping.data();

  double ener;
  std::vector<VALUETYPE> force_, virial;
  // Empty charge_spin triggers default_chg_spin_ fallback ([0.0, 1.0])
  dp.compute(ener, force_, virial, coord_cpy, atype_cpy, box, nall - nloc,
             inlist, 0);
  std::vector<VALUETYPE> force;
  _fold_back<VALUETYPE>(force, force_, mapping, nloc, nall, 3);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}
