// SPDX-License-Identifier: LGPL-3.0-or-later
// Test C++ inference for PT (.pth) backend with DPA2 (mixed-type) model.
// Reference values generated by source/tests/infer/gen_dpa2.py.
#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <fstream>
#include <vector>

#include "DeepPot.h"
#include "neighbor_list.h"
#include "test_utils.h"

// DPA2 models need relaxed epsilon for float32 due to attention layers
#undef EPSILON
#define EPSILON (std::is_same<VALUETYPE, double>::value ? 1e-7 : 1e-4)

template <class VALUETYPE>
class TestInferDeepPotDpa2Pt : public ::testing::Test {
 protected:
  std::vector<VALUETYPE> coord = {12.83, 2.56, 2.18, 12.09, 2.87, 2.74,
                                  00.25, 3.32, 1.68, 3.36,  3.00, 1.81,
                                  3.51,  2.51, 2.60, 4.27,  3.22, 1.56};
  std::vector<int> atype = {0, 1, 1, 0, 1, 1};
  std::vector<VALUETYPE> box = {13., 0., 0., 0., 13., 0., 0., 0., 13.};
  // Generated by source/tests/infer/gen_dpa2.py (PBC)
  // Same weights as deeppot_dpa2.pt2
  std::vector<VALUETYPE> expected_e = {
      7.071627938744207142e-02, 8.956842892510968879e-02,
      8.960487851717680030e-02, 7.041307335741320284e-02,
      8.946246778628771934e-02, 8.950273290096630308e-02};
  std::vector<VALUETYPE> expected_f = {
      -5.274693721628801856e-04, 1.193250440811189066e-03,
      1.867294153282934117e-04,  2.490457803117060009e-03,
      2.083159497669665578e-04,  -2.131291141610240462e-03,
      -1.979320483395129171e-03, -1.407207733401788464e-03,
      1.949836307851203227e-03,  1.915769838158783156e-03,
      -6.293858809443212809e-04, 1.198454068477057414e-03,
      1.072803472681185637e-03,  2.312144719396729171e-03,
      -3.535229553224201668e-03, -2.972241258399019662e-03,
      -1.677117495628775105e-03, 2.331500903177888620e-03};
  std::vector<VALUETYPE> expected_v = {
      1.517438219904506140e-04,  3.153641070825828705e-05,
      9.592624160681313423e-04,  1.512258434675041886e-03,
      -1.374312681808020995e-03, 2.336195918698237822e-04,
      -3.333563799352665547e-04, 2.508037892144997054e-04,
      -8.530908676130223665e-04, -1.648192206593849162e-03,
      1.139229474487762515e-04,  7.262981059689609326e-04,
      -5.912655960190413024e-04, 3.191721961395713810e-04,
      4.032426542912010792e-04,  1.491502657559045861e-03,
      -1.574217190862803577e-04, -6.875599765903525531e-04,
      -1.172563372550058675e-03, -8.714771871140328773e-04,
      7.011614650317343159e-04,  -1.644887030084397038e-03,
      5.266671463186511828e-05,  1.823841393156752145e-04,
      1.227078953241444483e-03,  7.256669776064127338e-04,
      -6.274876719194932752e-04, -1.732702232782646701e-03,
      -2.907896824664109634e-05, -1.531684598556129744e-04,
      -5.765915598519781951e-05, -5.233315267730154338e-04,
      8.197518693585480057e-04,  -1.145904850968312741e-04,
      8.228334341042128908e-04,  -1.309755110431354069e-03,
      1.263283100941724408e-04,  -6.499776597446308216e-04,
      1.041035279848752512e-03,  -1.266370818144572821e-04,
      -6.309984851702504565e-04, 9.829003029184085489e-04,
      2.172809307868736898e-04,  9.264667977179697270e-04,
      -1.439968658957715671e-03, -8.850345766150289825e-04,
      -4.995478668532852586e-04, 6.942600029958925258e-04,
      -9.964318945735069471e-04, -3.475307206780771938e-04,
      4.421486462026064622e-04,  1.480933133502598115e-03,
      4.956979243994461166e-04,  -6.243338853763658915e-04};
  int natoms;
  double expected_tot_e;
  std::vector<VALUETYPE> expected_tot_v;

  deepmd::DeepPot dp;

  void SetUp() override {
#ifndef BUILD_PYTORCH
    GTEST_SKIP() << "Skip because PyTorch support is not enabled.";
#endif
    dp.init("../../tests/infer/deeppot_dpa2.pth");

    natoms = expected_e.size();
    EXPECT_EQ(natoms * 3, expected_f.size());
    EXPECT_EQ(natoms * 9, expected_v.size());
    expected_tot_e = 0.;
    expected_tot_v.resize(9);
    std::fill(expected_tot_v.begin(), expected_tot_v.end(), 0.);
    for (int ii = 0; ii < natoms; ++ii) {
      expected_tot_e += expected_e[ii];
    }
    for (int ii = 0; ii < natoms; ++ii) {
      for (int dd = 0; dd < 9; ++dd) {
        expected_tot_v[dd] += expected_v[ii * 9 + dd];
      }
    }
  };

  void TearDown() override {};
};

TYPED_TEST_SUITE(TestInferDeepPotDpa2Pt, ValueTypes);

TYPED_TEST(TestInferDeepPotDpa2Pt, cpu_build_nlist) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  deepmd::DeepPot& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, virial;
  dp.compute(ener, force, virial, coord, atype, box);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(virial.size(), 9);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepPotDpa2Pt, cpu_build_nlist_atomic) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_e = this->expected_e;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  std::vector<VALUETYPE>& expected_v = this->expected_v;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  deepmd::DeepPot& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, virial, atom_ener, atom_vir;
  dp.compute(ener, force, virial, atom_ener, atom_vir, coord, atype, box);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(virial.size(), 9);
  EXPECT_EQ(atom_ener.size(), natoms);
  EXPECT_EQ(atom_vir.size(), natoms * 9);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
  for (int ii = 0; ii < natoms; ++ii) {
    EXPECT_LT(fabs(atom_ener[ii] - expected_e[ii]), EPSILON);
  }
  for (int ii = 0; ii < natoms * 9; ++ii) {
    EXPECT_LT(fabs(atom_vir[ii] - expected_v[ii]), EPSILON);
  }
}

template <class VALUETYPE>
class TestInferDeepPotDpa2PtNoPbc : public ::testing::Test {
 protected:
  std::vector<VALUETYPE> coord = {12.83, 2.56, 2.18, 12.09, 2.87, 2.74,
                                  00.25, 3.32, 1.68, 3.36,  3.00, 1.81,
                                  3.51,  2.51, 2.60, 4.27,  3.22, 1.56};
  std::vector<int> atype = {0, 1, 1, 0, 1, 1};
  std::vector<VALUETYPE> box = {};
  // Generated by source/tests/infer/gen_dpa2.py (NoPbc)
  std::vector<VALUETYPE> expected_e = {
      7.040088508308872672e-02, 8.982469559367040057e-02,
      8.577623946212942219e-02, 7.040934177879884515e-02,
      8.945548314285678426e-02, 8.949825740664299478e-02};
  std::vector<VALUETYPE> expected_f = {
      -1.861122162562435728e-03, 7.796592843166958754e-04,
      1.408416771668870304e-03,  1.861122162562435728e-03,
      -7.796592843166958754e-04, -1.408416771668870304e-03,
      7.989858611689789158e-06,  -8.882999958486996055e-07,
      6.245020643919394922e-07,  1.902754128669860347e-03,
      -6.352329301743543221e-04, 1.207752494569338045e-03,
      1.070369236473196111e-03,  2.315002648400190776e-03,
      -3.541311301960455016e-03, -2.981113223754746147e-03,
      -1.678881418229987875e-03, 2.332934305326725324e-03};
  std::vector<VALUETYPE> expected_v = {
      -6.127996334459595573e-04, 2.567133599570932054e-04,
      4.637402631482920312e-04,  2.567133599570871338e-04,
      -1.075420832252682243e-04, -1.942695696972585040e-04,
      4.637402631482885618e-04,  -1.942695696972585040e-04,
      -3.509385775176268943e-04, -7.644307668502429987e-04,
      3.202345104372618725e-04,  5.784881478866719245e-04,
      3.202345104372679441e-04,  -1.341522949129076922e-04,
      -2.423396295200912730e-04, 5.784881478866736593e-04,
      -2.423396295200912730e-04, -4.377748146169404588e-04,
      -3.513757860850363137e-05, 3.832988937821590170e-06,
      -2.110944049426024960e-06, 3.720402587844924420e-06,
      -4.467285354302484369e-07, 2.713133828440792358e-07,
      -2.247594248243392140e-06, 3.038521155323589437e-07,
      -2.043480298083789665e-07, -1.805285605745314374e-03,
      -3.299108526406708403e-05, -1.433503553029593508e-04,
      -5.634907459799816040e-05, -5.244497082627216575e-04,
      8.225112559487391447e-04,  -1.066279487329045012e-04,
      8.250564344742740593e-04,  -1.314627112018488739e-03,
      1.418428782329920687e-04,  -6.489353301914278088e-04,
      1.040194879737597151e-03,  -1.290554683731088420e-04,
      -6.315169755139156751e-04, 9.836240801541270423e-04,
      2.191667463880570682e-04,  9.277526988634050842e-04,
      -1.441866538661381973e-03, -8.785258023073679035e-04,
      -4.996756538244960522e-04, 6.950977407477803779e-04,
      -9.960849399589096972e-04, -3.475760534132951024e-04,
      4.422812763073963316e-04,  1.479540117726085499e-03,
      4.955749403398957212e-04,  -6.242526914391316982e-04};
  int natoms;
  double expected_tot_e;
  std::vector<VALUETYPE> expected_tot_v;

  deepmd::DeepPot dp;

  void SetUp() override {
#ifndef BUILD_PYTORCH
    GTEST_SKIP() << "Skip because PyTorch support is not enabled.";
#endif
    dp.init("../../tests/infer/deeppot_dpa2.pth");

    natoms = expected_e.size();
    EXPECT_EQ(natoms * 3, expected_f.size());
    EXPECT_EQ(natoms * 9, expected_v.size());
    expected_tot_e = 0.;
    expected_tot_v.resize(9);
    std::fill(expected_tot_v.begin(), expected_tot_v.end(), 0.);
    for (int ii = 0; ii < natoms; ++ii) {
      expected_tot_e += expected_e[ii];
    }
    for (int ii = 0; ii < natoms; ++ii) {
      for (int dd = 0; dd < 9; ++dd) {
        expected_tot_v[dd] += expected_v[ii * 9 + dd];
      }
    }
  };

  void TearDown() override {};
};

TYPED_TEST_SUITE(TestInferDeepPotDpa2PtNoPbc, ValueTypes);

TYPED_TEST(TestInferDeepPotDpa2PtNoPbc, cpu_build_nlist) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  deepmd::DeepPot& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, virial;
  dp.compute(ener, force, virial, coord, atype, box);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(virial.size(), 9);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepPotDpa2PtNoPbc, cpu_lmp_nlist) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  deepmd::DeepPot& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, virial;

  std::vector<std::vector<int> > nlist_data = {
      {1, 2, 3, 4, 5}, {0, 2, 3, 4, 5}, {0, 1, 3, 4, 5},
      {0, 1, 2, 4, 5}, {0, 1, 2, 3, 5}, {0, 1, 2, 3, 4}};
  std::vector<int> ilist(natoms), numneigh(natoms);
  std::vector<int*> firstneigh(natoms);
  deepmd::InputNlist inlist(natoms, &ilist[0], &numneigh[0], &firstneigh[0]);
  convert_nlist(inlist, nlist_data);
  dp.compute(ener, force, virial, coord, atype, box, 0, inlist, 0);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(virial.size(), 9);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}
