// SPDX-License-Identifier: LGPL-3.0-or-later
// Test C++ inference for the PT (.pth) backend with charge_spin input (DPA3).
// Model + reference generated by source/tests/infer/gen_chg_spin.py.
//
// Mirrors the DPA3 .pth test layout (test_deeppot_dpa3_pt.cc): the PBC case
// exercises the standalone path (forward), and the NoPbc case exercises the
// LAMMPS neighbor-list path (forward_lower) without ghost atoms.  Both cases
// cover explicit charge_spin and the default_chg_spin fallback.
#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <fstream>
#include <vector>

#include "DeepPot.h"
#include "expected_ref.h"
#include "neighbor_list.h"
#include "test_utils.h"

#undef EPSILON
#define EPSILON (std::is_same<VALUETYPE, double>::value ? 1e-10 : 1e-4)

namespace {
constexpr const char* kRefPath = "../../tests/infer/chg_spin.expected";
constexpr const char* kModelPath = "../../tests/infer/chg_spin.pth";
}  // namespace

// ---------------------------------------------------------------------------
// PBC: standalone path (DeepPot::compute that builds its own nlist -> forward)
// ---------------------------------------------------------------------------
template <class VALUETYPE>
class TestInferDeepPotChgSpinPt : public ::testing::Test {
 protected:
  std::vector<VALUETYPE> coord = {12.83, 2.56, 2.18, 12.09, 2.87, 2.74,
                                  00.25, 3.32, 1.68, 3.36,  3.00, 1.81,
                                  3.51,  2.51, 2.60, 4.27,  3.22, 1.56};
  std::vector<int> atype = {0, 1, 1, 0, 1, 1};
  std::vector<VALUETYPE> box = {13., 0., 0., 0., 13., 0., 0., 0., 13.};
  // charge_spin is always double regardless of VALUETYPE.
  // [1.0, 2.0] maps to charge idx 101, spin idx 2 — both differ from the
  // model's default_chg_spin [0.0, 1.0] (charge idx 100, spin idx 1).
  std::vector<double> charge_spin_explicit = {1.0, 2.0};

  std::vector<VALUETYPE> expected_f_explicit, expected_f_default;
  int natoms;
  double expected_tot_e_explicit, expected_tot_e_default;
  std::vector<VALUETYPE> expected_tot_v_explicit, expected_tot_v_default;

  deepmd::DeepPot dp;

  static void accumulate(const std::vector<VALUETYPE>& e,
                         const std::vector<VALUETYPE>& v,
                         double& tot_e,
                         std::vector<VALUETYPE>& tot_v) {
    int n = e.size();
    tot_e = 0.;
    tot_v.assign(9, 0.);
    for (int ii = 0; ii < n; ++ii) {
      tot_e += e[ii];
      for (int dd = 0; dd < 9; ++dd) {
        tot_v[dd] += v[ii * 9 + dd];
      }
    }
  }

  void SetUp() override {
#ifndef BUILD_PYTORCH
    GTEST_SKIP() << "Skip because PyTorch support is not enabled.";
#endif
    deepmd_test::ExpectedRef ref;
    ref.load(kRefPath);
    std::vector<VALUETYPE> e_exp = ref.get<VALUETYPE>("explicit", "expected_e");
    std::vector<VALUETYPE> e_def = ref.get<VALUETYPE>("default", "expected_e");
    expected_f_explicit = ref.get<VALUETYPE>("explicit", "expected_f");
    expected_f_default = ref.get<VALUETYPE>("default", "expected_f");
    accumulate(e_exp, ref.get<VALUETYPE>("explicit", "expected_v"),
               expected_tot_e_explicit, expected_tot_v_explicit);
    accumulate(e_def, ref.get<VALUETYPE>("default", "expected_v"),
               expected_tot_e_default, expected_tot_v_default);
    natoms = e_exp.size();

    {
      std::ifstream model_file(kModelPath);
      if (!model_file.good()) {
        GTEST_SKIP() << "Skip because " << kModelPath
                     << " was not generated (e.g. .pth export was skipped).";
      }
    }
    dp.init(kModelPath);
  }

  void TearDown() override {}
};

TYPED_TEST_SUITE(TestInferDeepPotChgSpinPt, ValueTypes);

TYPED_TEST(TestInferDeepPotChgSpinPt, dim_chg_spin) {
  deepmd::DeepPot& dp = this->dp;
  EXPECT_EQ(dp.dim_chg_spin(), 2);
}

// Charge and multiplicity index one row each of an embedding table, and
// neither the gather nor the kernel bounds-checks the row, so a state the
// tables cannot address has to be refused where it is installed.
TYPED_TEST(TestInferDeepPotChgSpinPt,
           set_charge_spin_takes_addressable_states) {
  deepmd::DeepPot& dp = this->dp;
  EXPECT_NO_THROW(dp.set_charge_spin({0.0, 1.0}));
  EXPECT_NO_THROW(dp.set_charge_spin({-100.0, 0.0}));
  EXPECT_NO_THROW(dp.set_charge_spin({99.0, 99.0}));
}

TYPED_TEST(TestInferDeepPotChgSpinPt,
           set_charge_spin_refuses_fractional_states) {
  deepmd::DeepPot& dp = this->dp;
  EXPECT_THROW(dp.set_charge_spin({0.5, 1.0}), deepmd::deepmd_exception);
  EXPECT_THROW(dp.set_charge_spin({0.0, 1.5}), deepmd::deepmd_exception);
}

TYPED_TEST(TestInferDeepPotChgSpinPt,
           set_charge_spin_refuses_states_off_table) {
  deepmd::DeepPot& dp = this->dp;
  EXPECT_THROW(dp.set_charge_spin({-101.0, 1.0}), deepmd::deepmd_exception);
  EXPECT_THROW(dp.set_charge_spin({100.0, 1.0}), deepmd::deepmd_exception);
  EXPECT_THROW(dp.set_charge_spin({0.0, -1.0}), deepmd::deepmd_exception);
  EXPECT_THROW(dp.set_charge_spin({0.0, 100.0}), deepmd::deepmd_exception);
}

// An installed state has to reach the evaluations that follow it, and a
// refused one has to leave the installed one alone: a caller that handles
// the exception would otherwise evaluate against a state nobody chose.
TYPED_TEST(TestInferDeepPotChgSpinPt, set_charge_spin_holds_for_later_calls) {
  using VALUETYPE = TypeParam;
  deepmd::DeepPot& dp = this->dp;
  dp.set_charge_spin(this->charge_spin_explicit);

  double installed, after_refusal;
  std::vector<VALUETYPE> force, virial;
  dp.compute(installed, force, virial, this->coord, this->atype, this->box);
  EXPECT_LT(fabs(installed - this->expected_tot_e_explicit), EPSILON);

  EXPECT_THROW(dp.set_charge_spin({0.5, 1.0}), deepmd::deepmd_exception);
  dp.compute(after_refusal, force, virial, this->coord, this->atype, this->box);
  EXPECT_DOUBLE_EQ(installed, after_refusal);
}

TYPED_TEST(TestInferDeepPotChgSpinPt, cpu_build_nlist_explicit) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<double>& charge_spin = this->charge_spin_explicit;
  std::vector<VALUETYPE>& expected_f = this->expected_f_explicit;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_explicit;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_explicit;
  deepmd::DeepPot& dp = this->dp;

  double ener;
  std::vector<VALUETYPE> force, virial;
  dp.compute(ener, force, virial, coord, atype, box, {}, {}, charge_spin);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepPotChgSpinPt, cpu_build_nlist_default) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_f = this->expected_f_default;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_default;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_default;
  deepmd::DeepPot& dp = this->dp;

  double ener;
  std::vector<VALUETYPE> force, virial;
  // Empty charge_spin triggers the default_chg_spin fallback ([0.0, 1.0]).
  dp.compute(ener, force, virial, coord, atype, box);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

// ---------------------------------------------------------------------------
// NoPbc: LAMMPS neighbor-list path (forward_lower), no ghost atoms.
// Mirrors test_deeppot_dpa3_pt.cc::TestInferDeepPotDpa3PtNoPbc.cpu_lmp_nlist.
// ---------------------------------------------------------------------------
template <class VALUETYPE>
class TestInferDeepPotChgSpinPtNoPbc : public ::testing::Test {
 protected:
  std::vector<VALUETYPE> coord = {12.83, 2.56, 2.18, 12.09, 2.87, 2.74,
                                  00.25, 3.32, 1.68, 3.36,  3.00, 1.81,
                                  3.51,  2.51, 2.60, 4.27,  3.22, 1.56};
  std::vector<int> atype = {0, 1, 1, 0, 1, 1};
  std::vector<VALUETYPE> box = {};
  std::vector<double> charge_spin_explicit = {1.0, 2.0};

  std::vector<VALUETYPE> expected_f_explicit, expected_f_default;
  int natoms;
  double expected_tot_e_explicit, expected_tot_e_default;
  std::vector<VALUETYPE> expected_tot_v_explicit, expected_tot_v_default;

  deepmd::DeepPot dp;

  static void accumulate(const std::vector<VALUETYPE>& e,
                         const std::vector<VALUETYPE>& v,
                         double& tot_e,
                         std::vector<VALUETYPE>& tot_v) {
    int n = e.size();
    tot_e = 0.;
    tot_v.assign(9, 0.);
    for (int ii = 0; ii < n; ++ii) {
      tot_e += e[ii];
      for (int dd = 0; dd < 9; ++dd) {
        tot_v[dd] += v[ii * 9 + dd];
      }
    }
  }

  void SetUp() override {
#ifndef BUILD_PYTORCH
    GTEST_SKIP() << "Skip because PyTorch support is not enabled.";
#endif
    deepmd_test::ExpectedRef ref;
    ref.load(kRefPath);
    std::vector<VALUETYPE> e_exp =
        ref.get<VALUETYPE>("nopbc_explicit", "expected_e");
    std::vector<VALUETYPE> e_def =
        ref.get<VALUETYPE>("nopbc_default", "expected_e");
    expected_f_explicit = ref.get<VALUETYPE>("nopbc_explicit", "expected_f");
    expected_f_default = ref.get<VALUETYPE>("nopbc_default", "expected_f");
    accumulate(e_exp, ref.get<VALUETYPE>("nopbc_explicit", "expected_v"),
               expected_tot_e_explicit, expected_tot_v_explicit);
    accumulate(e_def, ref.get<VALUETYPE>("nopbc_default", "expected_v"),
               expected_tot_e_default, expected_tot_v_default);
    natoms = e_exp.size();

    {
      std::ifstream model_file(kModelPath);
      if (!model_file.good()) {
        GTEST_SKIP() << "Skip because " << kModelPath
                     << " was not generated (e.g. .pth export was skipped).";
      }
    }
    dp.init(kModelPath);
  }

  void TearDown() override {}
};

TYPED_TEST_SUITE(TestInferDeepPotChgSpinPtNoPbc, ValueTypes);

TYPED_TEST(TestInferDeepPotChgSpinPtNoPbc, cpu_lmp_nlist_explicit) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<double>& charge_spin = this->charge_spin_explicit;
  std::vector<VALUETYPE>& expected_f = this->expected_f_explicit;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_explicit;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_explicit;
  deepmd::DeepPot& dp = this->dp;

  std::vector<std::vector<int>> nlist_data = {{1, 2, 3, 4, 5}, {0, 2, 3, 4, 5},
                                              {0, 1, 3, 4, 5}, {0, 1, 2, 4, 5},
                                              {0, 1, 2, 3, 5}, {0, 1, 2, 3, 4}};
  std::vector<int> ilist(natoms), numneigh(natoms);
  std::vector<int*> firstneigh(natoms);
  deepmd::InputNlist inlist(natoms, &ilist[0], &numneigh[0], &firstneigh[0]);
  convert_nlist(inlist, nlist_data);

  double ener;
  std::vector<VALUETYPE> force, virial;
  dp.compute(ener, force, virial, coord, atype, box, 0, inlist, 0, {}, {},
             charge_spin);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepPotChgSpinPtNoPbc, cpu_lmp_nlist_default) {
  using VALUETYPE = TypeParam;
  std::vector<VALUETYPE>& coord = this->coord;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_f = this->expected_f_default;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v_default;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e_default;
  deepmd::DeepPot& dp = this->dp;

  std::vector<std::vector<int>> nlist_data = {{1, 2, 3, 4, 5}, {0, 2, 3, 4, 5},
                                              {0, 1, 3, 4, 5}, {0, 1, 2, 4, 5},
                                              {0, 1, 2, 3, 5}, {0, 1, 2, 3, 4}};
  std::vector<int> ilist(natoms), numneigh(natoms);
  std::vector<int*> firstneigh(natoms);
  deepmd::InputNlist inlist(natoms, &ilist[0], &numneigh[0], &firstneigh[0]);
  convert_nlist(inlist, nlist_data);

  double ener;
  std::vector<VALUETYPE> force, virial;
  // Empty charge_spin triggers the default_chg_spin fallback ([0.0, 1.0]).
  dp.compute(ener, force, virial, coord, atype, box, 0, inlist, 0);

  EXPECT_EQ(force.size(), static_cast<size_t>(natoms * 3));
  EXPECT_EQ(virial.size(), 9u);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
  }
  for (int ii = 0; ii < 9; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}
