// SPDX-License-Identifier: LGPL-3.0-or-later
// Test C++ inference for pt_expt (.pt2) backend with DPA1 spin model.
#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <fstream>
#include <vector>

#include "DeepSpin.h"
#include "neighbor_list.h"
#include "test_utils.h"

// Spin models need relaxed epsilon
#undef EPSILON
#define EPSILON (std::is_same<VALUETYPE, double>::value ? 1e-6 : 1e-1)

// ============================================================================
// PBC test fixture
// ============================================================================

template <class VALUETYPE>
class TestInferDeepSpinDpaPtExpt : public ::testing::Test {
 protected:
  std::vector<VALUETYPE> coord = {12.83, 2.56, 2.18, 12.09, 2.87, 2.74,
                                  00.25, 3.32, 1.68, 3.36,  3.00, 1.81,
                                  3.51,  2.51, 2.60, 4.27,  3.22, 1.56};
  std::vector<VALUETYPE> spin = {0.13, 0.02, 0.03, 0., 0., 0., 0., 0., 0.,
                                 0.14, 0.10, 0.12, 0., 0., 0., 0., 0., 0.};
  std::vector<int> atype = {0, 1, 1, 0, 1, 1};
  std::vector<VALUETYPE> box = {13., 0., 0., 0., 13., 0., 0., 0., 13.};

  // Reference values generated by source/tests/infer/gen_spin.py
  std::vector<VALUETYPE> expected_e;
  std::vector<VALUETYPE> expected_f;
  std::vector<VALUETYPE> expected_fm;
  std::vector<VALUETYPE> expected_tot_v;
  std::vector<VALUETYPE> expected_atom_v;

  int natoms;
  double expected_tot_e;

  deepmd::DeepSpin dp;

  void SetUp() override {
    // The .pt2 spin model requires the BUILD_PT_EXPT guard from the header.
    // If AOTInductor headers are missing, skip.
    std::string model_path = "../../tests/infer/deeppot_dpa_spin.pt2";
    {
      std::ifstream f(model_path);
      if (!f.good()) {
        GTEST_SKIP() << "Skipping: " << model_path << " not found.";
      }
    }
#ifndef BUILD_PYTORCH
    GTEST_SKIP() << "Skip because PyTorch support is not enabled.";
#endif
    dp.init(model_path);

    // PBC reference values from gen_spin.py
    expected_e = {
        -4.736511666341149118e-02, 2.663324583045018068e-01,
        2.662707880956619588e-01,  -4.025182706753409334e-02,
        2.661383816099721633e-01,  2.663717506235512844e-01,
    };
    expected_f = {
        1.309983290673980352e-02,  6.799786488006153221e-03,
        6.649738725468718609e-03,  -1.144456277614634265e-03,
        -3.728471118137270928e-03, -6.491178701583714961e-03,
        -5.361730092721230315e-03, -2.772299524882485336e-03,
        -4.492382686597841141e-04, 6.983026947998328959e-03,
        5.505263649468144886e-03,  1.166735707547454995e-02,
        -5.356940629013495075e-03, -1.082410608691008200e-03,
        -8.305081927004348899e-03, -8.219732855388919845e-03,
        -4.721868885763546436e-03, -3.071596903695449424e-03,
    };
    expected_fm = {
        -2.702014342752852571e-01, -1.027058879186482226e-01,
        -7.359539608958531876e-02, 0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  4.837763296762351284e-02,
        7.279460222389372293e-02,  5.692337419156127953e-02,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
    };
    expected_tot_v = {
        -3.296409925977442784e-02, -6.514341112515736193e-03,
        2.302568866291881608e-03,  -3.920085383179669654e-03,
        -3.902770613936823105e-03, -2.657953604957638679e-04,
        1.599970898976528456e-03,  1.167950771447608766e-03,
        -9.311107385533376815e-03,
    };
    expected_atom_v = {
        -3.317500147651446761e-03, -5.453620106200618781e-04,
        1.253012128253723576e-03,  -4.341313022555767223e-04,
        -8.474261758929188017e-04, 3.158911084565297830e-04,
        1.428597590986904363e-03,  3.418340644092453598e-04,
        -1.048232718033599879e-03, 2.743654218857313667e-03,
        -7.881895490872514818e-04, -2.104426693877021765e-03,
        1.962048943234902601e-03,  -1.049310174771551311e-03,
        -1.494575973896533887e-03, 3.408026024086528976e-03,
        -1.712970751848944505e-03, -2.576173589596463843e-03,
        -1.201918779945609916e-02, -4.491798568020247129e-03,
        3.096386035183865820e-03,  9.950813669892615530e-04,
        -7.365361184918026161e-04, 9.845327634837373713e-05,
        -1.426610186908689078e-03, -1.277523649606296732e-03,
        1.099298580748801768e-03,  -4.322845112754755692e-03,
        -5.390493138998655141e-04, 8.445031349176490218e-04,
        -9.915231731252361659e-04, -6.214579519519495155e-04,
        9.500409608549969988e-04,  8.491271635631678690e-04,
        9.275347724790529869e-04,  -1.452342638958830420e-03,
        -1.981095983149218712e-03, 2.124416489228214862e-03,
        -3.803001677309152204e-03, 7.469960084091023956e-06,
        1.440128580078422951e-03,  -2.264550990055120075e-03,
        -1.502942461627763959e-03, 2.647480428239051657e-03,
        -4.361425384715853296e-03, -5.960350980804883167e-03,
        -1.029717381562808348e-03, 8.970464384536506412e-04,
        -3.828067017971811641e-03, -8.614074432427376669e-04,
        9.393899863778386750e-04,  -3.397832689085407594e-03,
        -8.981477278037544023e-04, 1.067175759602119771e-03,
    };

    natoms = expected_e.size();
    EXPECT_EQ(natoms * 3, expected_f.size());
    EXPECT_EQ(natoms * 3, expected_fm.size());
    EXPECT_EQ(9, expected_tot_v.size());
    EXPECT_EQ(natoms * 9, expected_atom_v.size());
    expected_tot_e = 0.;
    for (int ii = 0; ii < natoms; ++ii) {
      expected_tot_e += expected_e[ii];
    }
  };

  void TearDown() override {};
};

TYPED_TEST_SUITE(TestInferDeepSpinDpaPtExpt, ValueTypes);

TYPED_TEST(TestInferDeepSpinDpaPtExpt, cpu_build_nlist) {
  using VALUETYPE = TypeParam;
  const std::vector<VALUETYPE>& coord = this->coord;
  const std::vector<VALUETYPE>& spin = this->spin;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_e = this->expected_e;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  std::vector<VALUETYPE>& expected_fm = this->expected_fm;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  deepmd::DeepSpin& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, force_mag, virial;
  dp.compute(ener, force, force_mag, virial, coord, spin, atype, box);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(force_mag.size(), natoms * 3);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
    EXPECT_LT(fabs(force_mag[ii] - expected_fm[ii]), EPSILON);
  }
  EXPECT_FALSE(virial.empty()) << "Virial should not be empty";
  EXPECT_EQ(virial.size(), 9);
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepSpinDpaPtExpt, cpu_build_nlist_atomic) {
  using VALUETYPE = TypeParam;
  const std::vector<VALUETYPE>& coord = this->coord;
  const std::vector<VALUETYPE>& spin = this->spin;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_e = this->expected_e;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  std::vector<VALUETYPE>& expected_fm = this->expected_fm;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  std::vector<VALUETYPE>& expected_atom_v = this->expected_atom_v;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  deepmd::DeepSpin& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, force_mag, virial, atom_ener, atom_vir;
  dp.compute(ener, force, force_mag, virial, atom_ener, atom_vir, coord, spin,
             atype, box);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(force_mag.size(), natoms * 3);
  EXPECT_EQ(atom_ener.size(), natoms);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
    EXPECT_LT(fabs(force_mag[ii] - expected_fm[ii]), EPSILON);
  }
  EXPECT_FALSE(virial.empty()) << "Virial should not be empty";
  EXPECT_EQ(virial.size(), 9);
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
  for (int ii = 0; ii < natoms; ++ii) {
    EXPECT_LT(fabs(atom_ener[ii] - expected_e[ii]), EPSILON);
  }
  EXPECT_FALSE(atom_vir.empty()) << "Atomic virial should not be empty";
  EXPECT_EQ(atom_vir.size(), natoms * 9);
  for (int ii = 0; ii < natoms * 9; ++ii) {
    EXPECT_LT(fabs(atom_vir[ii] - expected_atom_v[ii]), EPSILON);
  }
}

// ============================================================================
// NoPBC test fixture
// ============================================================================

template <class VALUETYPE>
class TestInferDeepSpinDpaPtExptNopbc : public ::testing::Test {
 protected:
  std::vector<VALUETYPE> coord = {12.83, 2.56, 2.18, 12.09, 2.87, 2.74,
                                  00.25, 3.32, 1.68, 3.36,  3.00, 1.81,
                                  3.51,  2.51, 2.60, 4.27,  3.22, 1.56};
  std::vector<VALUETYPE> spin = {0.13, 0.02, 0.03, 0., 0., 0., 0., 0., 0.,
                                 0.14, 0.10, 0.12, 0., 0., 0., 0., 0., 0.};
  std::vector<int> atype = {0, 1, 1, 0, 1, 1};
  std::vector<VALUETYPE> box = {};

  // Reference values for NoPBC from gen_spin.py
  std::vector<VALUETYPE> expected_e;
  std::vector<VALUETYPE> expected_f;
  std::vector<VALUETYPE> expected_fm;
  std::vector<VALUETYPE> expected_tot_v;
  std::vector<VALUETYPE> expected_atom_v;

  int natoms;
  double expected_tot_e;

  deepmd::DeepSpin dp;

  void SetUp() override {
    std::string model_path = "../../tests/infer/deeppot_dpa_spin.pt2";
    {
      std::ifstream f(model_path);
      if (!f.good()) {
        GTEST_SKIP() << "Skipping: " << model_path << " not found.";
      }
    }
#ifndef BUILD_PYTORCH
    GTEST_SKIP() << "Skip because PyTorch support is not enabled.";
#endif
    dp.init(model_path);

    // NoPBC reference values from gen_spin.py
    expected_e = {
        -4.263824715539775434e-02, 2.659531961465150807e-01,
        2.679077652998275716e-01,  -4.042215423551187570e-02,
        2.666009600722629158e-01,  2.666060991401024149e-01,
    };
    expected_f = {
        9.664606789041574331e-04,  4.875258490407333167e-03,
        8.372291856602237514e-03,  -9.664606789041574331e-04,
        -4.875258490407331433e-03, -8.372291856602209759e-03,
        3.462063530624336170e-03,  -3.516414654756409722e-04,
        1.540231672543395411e-04,  9.145994016724501297e-03,
        6.127039584892107760e-03,  1.114133934233926815e-02,
        -5.161415144547300271e-03, -1.229667699599260294e-03,
        -8.053323256964733598e-03, -7.446642402801547170e-03,
        -4.545730419817223950e-03, -3.242039252628891276e-03,
    };
    expected_fm = {
        2.426746573908480920e-02,  -2.632265214292328626e-02,
        -4.622069216845703377e-02, 0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  5.019524717501219757e-02,
        7.318340727755086317e-02,  5.710550212233043987e-02,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
        0.000000000000000000e+00,  0.000000000000000000e+00,
    };
    expected_tot_v = {
        -1.760249353608427103e-02, 1.699089611551340799e-03,
        -3.207143602659518616e-03, 3.802314035573836626e-04,
        -2.021378920534677454e-03, -2.519436241845334455e-03,
        1.558229715287920425e-03,  6.867566983090854244e-04,
        -1.026012201128513081e-02,
    };
    expected_atom_v = {
        -9.010484131816154374e-04, 3.774662271365247790e-04,
        6.818744748307292713e-04,  3.700909920694162025e-04,
        -1.550381183003379792e-04, -2.800688588649180577e-04,
        6.691585522995424640e-04,  -2.803231773155778761e-04,
        -5.063902557961297290e-04, 2.068893745514948854e-03,
        -8.666987312292658875e-04, -1.565649320930233464e-03,
        3.054535161074109495e-03,  -1.279602567476957262e-03,
        -2.311540121893843058e-03, 5.195098769247979975e-03,
        -2.176325160090315791e-03, -3.931426095646995550e-03,
        -9.856122919086314146e-03, 9.936684925752666681e-04,
        -3.439719552552561802e-04, 1.052798535866198608e-03,
        -9.900711767116699563e-05, 2.762122318620294312e-05,
        -5.083128431155595943e-04, 4.192561625213921898e-05,
        -5.371277558265975804e-06, -1.703601525016029683e-03,
        -2.250342243479974691e-04, 2.948710405297760850e-04,
        -2.741660339186102746e-04, -5.140178418111540637e-04,
        7.694906072377993844e-04,  3.213894451938870134e-04,
        7.860699694575146168e-04,  -1.201682807120130203e-03,
        -5.723947614714765264e-04, 2.340653893581970402e-03,
        -3.822101811639220734e-03, -1.559120189565561809e-04,
        1.375865762882331946e-03,  -2.173696052105959873e-03,
        -1.277932982926627964e-03, 2.762213706055685614e-03,
        -4.518197398377981483e-03, -4.806069982039730404e-03,
        -8.457891679641386939e-04, 8.142858536873513742e-04,
        -3.629730539376156001e-03, -8.154749344004806610e-04,
        8.996120390360722724e-04,  -3.613530537932585843e-03,
        -9.502343452691061620e-04, 1.113518176527171326e-03,
    };

    natoms = expected_e.size();
    EXPECT_EQ(natoms * 3, expected_f.size());
    EXPECT_EQ(natoms * 3, expected_fm.size());
    EXPECT_EQ(9, expected_tot_v.size());
    EXPECT_EQ(natoms * 9, expected_atom_v.size());
    expected_tot_e = 0.;
    for (int ii = 0; ii < natoms; ++ii) {
      expected_tot_e += expected_e[ii];
    }
  };

  void TearDown() override {};
};

TYPED_TEST_SUITE(TestInferDeepSpinDpaPtExptNopbc, ValueTypes);

TYPED_TEST(TestInferDeepSpinDpaPtExptNopbc, cpu_build_nlist) {
  using VALUETYPE = TypeParam;
  const std::vector<VALUETYPE>& coord = this->coord;
  const std::vector<VALUETYPE>& spin = this->spin;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_e = this->expected_e;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  std::vector<VALUETYPE>& expected_fm = this->expected_fm;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  deepmd::DeepSpin& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, force_mag, virial;
  dp.compute(ener, force, force_mag, virial, coord, spin, atype, box);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(force_mag.size(), natoms * 3);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
    EXPECT_LT(fabs(force_mag[ii] - expected_fm[ii]), EPSILON);
  }
  EXPECT_FALSE(virial.empty()) << "Virial should not be empty";
  EXPECT_EQ(virial.size(), 9);
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepSpinDpaPtExptNopbc, cpu_build_nlist_atomic) {
  using VALUETYPE = TypeParam;
  const std::vector<VALUETYPE>& coord = this->coord;
  const std::vector<VALUETYPE>& spin = this->spin;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_e = this->expected_e;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  std::vector<VALUETYPE>& expected_fm = this->expected_fm;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  std::vector<VALUETYPE>& expected_atom_v = this->expected_atom_v;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  deepmd::DeepSpin& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, force_mag, virial, atom_ener, atom_vir;
  dp.compute(ener, force, force_mag, virial, atom_ener, atom_vir, coord, spin,
             atype, box);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(force_mag.size(), natoms * 3);
  EXPECT_EQ(atom_ener.size(), natoms);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
    EXPECT_LT(fabs(force_mag[ii] - expected_fm[ii]), EPSILON);
  }
  EXPECT_FALSE(virial.empty()) << "Virial should not be empty";
  EXPECT_EQ(virial.size(), 9);
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
  for (int ii = 0; ii < natoms; ++ii) {
    EXPECT_LT(fabs(atom_ener[ii] - expected_e[ii]), EPSILON);
  }
  EXPECT_FALSE(atom_vir.empty()) << "Atomic virial should not be empty";
  EXPECT_EQ(atom_vir.size(), natoms * 9);
  for (int ii = 0; ii < natoms * 9; ++ii) {
    EXPECT_LT(fabs(atom_vir[ii] - expected_atom_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepSpinDpaPtExptNopbc, cpu_lmp_nlist) {
  using VALUETYPE = TypeParam;
  const std::vector<VALUETYPE>& coord = this->coord;
  const std::vector<VALUETYPE>& spin = this->spin;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_e = this->expected_e;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  std::vector<VALUETYPE>& expected_fm = this->expected_fm;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  deepmd::DeepSpin& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, force_mag, virial;

  std::vector<std::vector<int> > nlist_data = {
      {1, 2, 3, 4, 5}, {0, 2, 3, 4, 5}, {0, 1, 3, 4, 5},
      {0, 1, 2, 4, 5}, {0, 1, 2, 3, 5}, {0, 1, 2, 3, 4}};
  std::vector<int> ilist(natoms), numneigh(natoms);
  std::vector<int*> firstneigh(natoms);
  deepmd::InputNlist inlist(natoms, &ilist[0], &numneigh[0], &firstneigh[0]);
  convert_nlist(inlist, nlist_data);
  dp.compute(ener, force, force_mag, virial, coord, spin, atype, box, 0, inlist,
             0);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(force_mag.size(), natoms * 3);
  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
    EXPECT_LT(fabs(force_mag[ii] - expected_fm[ii]), EPSILON);
  }
  EXPECT_FALSE(virial.empty()) << "Virial should not be empty";
  EXPECT_EQ(virial.size(), 9);
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
}

TYPED_TEST(TestInferDeepSpinDpaPtExptNopbc, cpu_lmp_nlist_atomic) {
  using VALUETYPE = TypeParam;
  const std::vector<VALUETYPE>& coord = this->coord;
  const std::vector<VALUETYPE>& spin = this->spin;
  std::vector<int>& atype = this->atype;
  std::vector<VALUETYPE>& box = this->box;
  std::vector<VALUETYPE>& expected_e = this->expected_e;
  std::vector<VALUETYPE>& expected_f = this->expected_f;
  std::vector<VALUETYPE>& expected_fm = this->expected_fm;
  std::vector<VALUETYPE>& expected_tot_v = this->expected_tot_v;
  std::vector<VALUETYPE>& expected_atom_v = this->expected_atom_v;
  int& natoms = this->natoms;
  double& expected_tot_e = this->expected_tot_e;
  deepmd::DeepSpin& dp = this->dp;
  double ener;
  std::vector<VALUETYPE> force, force_mag, virial, atom_ener, atom_vir;

  std::vector<std::vector<int> > nlist_data = {
      {1, 2, 3, 4, 5}, {0, 2, 3, 4, 5}, {0, 1, 3, 4, 5},
      {0, 1, 2, 4, 5}, {0, 1, 2, 3, 5}, {0, 1, 2, 3, 4}};
  std::vector<int> ilist(natoms), numneigh(natoms);
  std::vector<int*> firstneigh(natoms);
  deepmd::InputNlist inlist(natoms, &ilist[0], &numneigh[0], &firstneigh[0]);
  convert_nlist(inlist, nlist_data);
  dp.compute(ener, force, force_mag, virial, atom_ener, atom_vir, coord, spin,
             atype, box, 0, inlist, 0);

  EXPECT_EQ(force.size(), natoms * 3);
  EXPECT_EQ(force_mag.size(), natoms * 3);
  EXPECT_EQ(atom_ener.size(), natoms);

  EXPECT_LT(fabs(ener - expected_tot_e), EPSILON);
  for (int ii = 0; ii < natoms * 3; ++ii) {
    EXPECT_LT(fabs(force[ii] - expected_f[ii]), EPSILON);
    EXPECT_LT(fabs(force_mag[ii] - expected_fm[ii]), EPSILON);
  }
  EXPECT_FALSE(virial.empty()) << "Virial should not be empty";
  EXPECT_EQ(virial.size(), 9);
  for (int ii = 0; ii < 3 * 3; ++ii) {
    EXPECT_LT(fabs(virial[ii] - expected_tot_v[ii]), EPSILON);
  }
  for (int ii = 0; ii < natoms; ++ii) {
    EXPECT_LT(fabs(atom_ener[ii] - expected_e[ii]), EPSILON);
  }
  EXPECT_FALSE(atom_vir.empty()) << "Atomic virial should not be empty";
  EXPECT_EQ(atom_vir.size(), natoms * 9);
  for (int ii = 0; ii < natoms * 9; ++ii) {
    EXPECT_LT(fabs(atom_vir[ii] - expected_atom_v[ii]), EPSILON);
  }
}
