on:
  pull_request_target:
    types:
      - "labeled"
name: Test CUDA
jobs:
  remove_label:
    permissions:
      contents: read
      pull-requests: write
    # so one can re-trigger the workflow without manually removing the label
    runs-on: ubuntu-latest
    if: github.repository_owner == 'deepmodeling' && github.event.label.name == 'Test CUDA'
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: Test CUDA
        number: ${{ github.event.pull_request.number }}
